# SPDX-License-Identifier: GPL-2.0
CFLAGS += $(KHDR_INCLUDES) -Wall

TEST_GEN_PROGS := nfsd_netlink_listener
TEST_GEN_PROGS += nfsd_lockd_netlink
TEST_GEN_PROGS += nfsd_netns_isolation
TEST_GEN_PROGS += nfsd_netns_stress

include ../lib.mk
