/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by xdrgen. Manual edits will be lost. */
/* XDR specification file: ../../Documentation/sunrpc/xdr/nfs3.x */
/* XDR specification modification time: Fri Nov 28 13:38:05 2025 */

#ifndef _LINUX_XDRGEN_NFS3_DEF_H
#define _LINUX_XDRGEN_NFS3_DEF_H

#include <linux/types.h>
#include <linux/sunrpc/xdrgen/_defs.h>

enum { NFS3_FHSIZE = 64 };

enum { NFS3_COOKIEVERFSIZE = 8 };

enum { NFS3_CREATEVERFSIZE = 8 };

enum { NFS3_WRITEVERFSIZE = 8 };

typedef u64 uint64;

typedef s64 int64;

typedef u32 uint32;

typedef s32 int32;

typedef string filename3;

typedef string nfspath3;

typedef uint64 fileid3;

typedef uint64 cookie3;

typedef u8 cookieverf3[NFS3_COOKIEVERFSIZE];

typedef u8 createverf3[NFS3_CREATEVERFSIZE];

typedef u8 writeverf3[NFS3_WRITEVERFSIZE];

typedef uint32 uid3;

typedef uint32 gid3;

typedef uint64 size3;

typedef uint64 offset3;

typedef uint32 mode3;

typedef uint32 count3;

enum nfsstat3 {
	NFS3_OK = 0,
	NFS3ERR_PERM = 1,
	NFS3ERR_NOENT = 2,
	NFS3ERR_IO = 5,
	NFS3ERR_NXIO = 6,
	NFS3ERR_ACCES = 13,
	NFS3ERR_EXIST = 17,
	NFS3ERR_XDEV = 18,
	NFS3ERR_NODEV = 19,
	NFS3ERR_NOTDIR = 20,
	NFS3ERR_ISDIR = 21,
	NFS3ERR_INVAL = 22,
	NFS3ERR_FBIG = 27,
	NFS3ERR_NOSPC = 28,
	NFS3ERR_ROFS = 30,
	NFS3ERR_MLINK = 31,
	NFS3ERR_NAMETOOLONG = 63,
	NFS3ERR_NOTEMPTY = 66,
	NFS3ERR_DQUOT = 69,
	NFS3ERR_STALE = 70,
	NFS3ERR_REMOTE = 71,
	NFS3ERR_BADHANDLE = 10001,
	NFS3ERR_NOT_SYNC = 10002,
	NFS3ERR_BAD_COOKIE = 10003,
	NFS3ERR_NOTSUPP = 10004,
	NFS3ERR_TOOSMALL = 10005,
	NFS3ERR_SERVERFAULT = 10006,
	NFS3ERR_BADTYPE = 10007,
	NFS3ERR_JUKEBOX = 10008,
};

typedef __be32 nfsstat3;

enum ftype3 {
	NF3REG = 1,
	NF3DIR = 2,
	NF3BLK = 3,
	NF3CHR = 4,
	NF3LNK = 5,
	NF3SOCK = 6,
	NF3FIFO = 7,
};

typedef enum ftype3 ftype3;

struct specdata3 {
	uint32 specdata1;
	uint32 specdata2;
};

struct nfs_fh3 {
	opaque data;
};

struct nfstime3 {
	uint32 seconds;
	uint32 nseconds;
};

struct fattr3 {
	ftype3 type;
	mode3 mode;
	uint32 nlink;
	uid3 uid;
	gid3 gid;
	size3 size;
	size3 used;
	struct specdata3 rdev;
	uint64 fsid;
	fileid3 fileid;
	struct nfstime3 atime;
	struct nfstime3 mtime;
	struct nfstime3 ctime;
};

struct post_op_attr {
	bool attributes_follow;
	union {
		struct fattr3 attributes;
	} u;
};

bool xdrgen_decode_post_op_attr(struct xdr_stream *xdr, struct post_op_attr *ptr);
bool xdrgen_encode_post_op_attr(struct xdr_stream *xdr, const struct post_op_attr *ptr);

struct wcc_attr {
	size3 size;
	struct nfstime3 mtime;
	struct nfstime3 ctime;
};

struct pre_op_attr {
	bool attributes_follow;
	union {
		struct wcc_attr attributes;
	} u;
};

struct wcc_data {
	struct pre_op_attr before;
	struct post_op_attr after;
};

struct post_op_fh3 {
	bool handle_follows;
	union {
		struct nfs_fh3 handle;
	} u;
};

enum time_how {
	DONT_CHANGE = 0,
	SET_TO_SERVER_TIME = 1,
	SET_TO_CLIENT_TIME = 2,
};

typedef enum time_how time_how;

struct set_mode3 {
	bool set_it;
	union {
		mode3 mode;
	} u;
};

struct set_uid3 {
	bool set_it;
	union {
		uid3 uid;
	} u;
};

struct set_gid3 {
	bool set_it;
	union {
		gid3 gid;
	} u;
};

struct set_size3 {
	bool set_it;
	union {
		size3 size;
	} u;
};

struct set_atime {
	time_how set_it;
	union {
		struct nfstime3 atime;
	} u;
};

struct set_mtime {
	time_how set_it;
	union {
		struct nfstime3 mtime;
	} u;
};

struct sattr3 {
	struct set_mode3 mode;
	struct set_uid3 uid;
	struct set_gid3 gid;
	struct set_size3 size;
	struct set_atime atime;
	struct set_mtime mtime;
};

struct diropargs3 {
	struct nfs_fh3 dir;
	filename3 name;
};

struct GETATTR3args {
	struct nfs_fh3 object;
};

struct GETATTR3resok {
	struct fattr3 obj_attributes;
};

struct GETATTR3res {
	nfsstat3 status;
	union {
		struct GETATTR3resok resok;
	} u;
};

struct sattrguard3 {
	bool check;
	union {
		struct nfstime3 obj_ctime;
	} u;
};

struct SETATTR3args {
	struct nfs_fh3 object;
	struct sattr3 new_attributes;
	struct sattrguard3 guard;
};

struct SETATTR3resok {
	struct wcc_data obj_wcc;
};

struct SETATTR3resfail {
	struct wcc_data obj_wcc;
};

struct SETATTR3res {
	nfsstat3 status;
	union {
		struct SETATTR3resok resok;
		struct SETATTR3resfail resfail;
	} u;
};

struct LOOKUP3args {
	struct diropargs3 what;
};

struct LOOKUP3resok {
	struct nfs_fh3 object;
	struct post_op_attr obj_attributes;
	struct post_op_attr dir_attributes;
};

struct LOOKUP3resfail {
	struct post_op_attr dir_attributes;
};

struct LOOKUP3res {
	nfsstat3 status;
	union {
		struct LOOKUP3resok resok;
		struct LOOKUP3resfail resfail;
	} u;
};

enum { ACCESS3_READ = 0x0001 };

enum { ACCESS3_LOOKUP = 0x0002 };

enum { ACCESS3_MODIFY = 0x0004 };

enum { ACCESS3_EXTEND = 0x0008 };

enum { ACCESS3_DELETE = 0x0010 };

enum { ACCESS3_EXECUTE = 0x0020 };

struct ACCESS3args {
	struct nfs_fh3 object;
	uint32 access;
};

struct ACCESS3resok {
	struct post_op_attr obj_attributes;
	uint32 access;
};

struct ACCESS3resfail {
	struct post_op_attr obj_attributes;
};

struct ACCESS3res {
	nfsstat3 status;
	union {
		struct ACCESS3resok resok;
		struct ACCESS3resfail resfail;
	} u;
};

struct READLINK3args {
	struct nfs_fh3 symlink;
};

struct READLINK3resok {
	struct post_op_attr symlink_attributes;
	nfspath3 data;
};

struct READLINK3resfail {
	struct post_op_attr symlink_attributes;
};

struct READLINK3res {
	nfsstat3 status;
	union {
		struct READLINK3resok resok;
		struct READLINK3resfail resfail;
	} u;
};

struct READ3args {
	struct nfs_fh3 file;
	offset3 offset;
	count3 count;
};

struct READ3resok {
	struct post_op_attr file_attributes;
	count3 count;
	bool eof;
	opaque data;
};

struct READ3resfail {
	struct post_op_attr file_attributes;
};

struct READ3res {
	nfsstat3 status;
	union {
		struct READ3resok resok;
		struct READ3resfail resfail;
	} u;
};

enum stable_how {
	UNSTABLE = 0,
	DATA_SYNC = 1,
	FILE_SYNC = 2,
};

typedef enum stable_how stable_how;

struct WRITE3args {
	struct nfs_fh3 file;
	offset3 offset;
	count3 count;
	stable_how stable;
	opaque data;
};

struct WRITE3resok {
	struct wcc_data file_wcc;
	count3 count;
	stable_how committed;
	writeverf3 verf;
};

struct WRITE3resfail {
	struct wcc_data file_wcc;
};

struct WRITE3res {
	nfsstat3 status;
	union {
		struct WRITE3resok resok;
		struct WRITE3resfail resfail;
	} u;
};

enum createmode3 {
	UNCHECKED = 0,
	GUARDED = 1,
	EXCLUSIVE = 2,
};

typedef enum createmode3 createmode3;

struct createhow3 {
	createmode3 mode;
	union {
		struct sattr3 obj_attributes;
		createverf3 verf;
	} u;
};

struct CREATE3args {
	struct diropargs3 where;
	struct createhow3 how;
};

struct CREATE3resok {
	struct post_op_fh3 obj;
	struct post_op_attr obj_attributes;
	struct wcc_data dir_wcc;
};

struct CREATE3resfail {
	struct wcc_data dir_wcc;
};

struct CREATE3res {
	nfsstat3 status;
	union {
		struct CREATE3resok resok;
		struct CREATE3resfail resfail;
	} u;
};

struct MKDIR3args {
	struct diropargs3 where;
	struct sattr3 attributes;
};

struct MKDIR3resok {
	struct post_op_fh3 obj;
	struct post_op_attr obj_attributes;
	struct wcc_data dir_wcc;
};

struct MKDIR3resfail {
	struct wcc_data dir_wcc;
};

struct MKDIR3res {
	nfsstat3 status;
	union {
		struct MKDIR3resok resok;
		struct MKDIR3resfail resfail;
	} u;
};

struct symlinkdata3 {
	struct sattr3 symlink_attributes;
	nfspath3 symlink_data;
};

struct SYMLINK3args {
	struct diropargs3 where;
	struct symlinkdata3 symlink;
};

struct SYMLINK3resok {
	struct post_op_fh3 obj;
	struct post_op_attr obj_attributes;
	struct wcc_data dir_wcc;
};

struct SYMLINK3resfail {
	struct wcc_data dir_wcc;
};

struct SYMLINK3res {
	nfsstat3 status;
	union {
		struct SYMLINK3resok resok;
		struct SYMLINK3resfail resfail;
	} u;
};

struct devicedata3 {
	struct sattr3 dev_attributes;
	struct specdata3 spec;
};

struct mknoddata3 {
	ftype3 type;
	union {
		struct devicedata3 device;
		struct sattr3 pipe_attributes;
	} u;
};

struct MKNOD3args {
	struct diropargs3 where;
	struct mknoddata3 what;
};

struct MKNOD3resok {
	struct post_op_fh3 obj;
	struct post_op_attr obj_attributes;
	struct wcc_data dir_wcc;
};

struct MKNOD3resfail {
	struct wcc_data dir_wcc;
};

struct MKNOD3res {
	nfsstat3 status;
	union {
		struct MKNOD3resok resok;
		struct MKNOD3resfail resfail;
	} u;
};

struct REMOVE3args {
	struct diropargs3 object;
};

struct REMOVE3resok {
	struct wcc_data dir_wcc;
};

struct REMOVE3resfail {
	struct wcc_data dir_wcc;
};

struct REMOVE3res {
	nfsstat3 status;
	union {
		struct REMOVE3resok resok;
		struct REMOVE3resfail resfail;
	} u;
};

struct RMDIR3args {
	struct diropargs3 object;
};

struct RMDIR3resok {
	struct wcc_data dir_wcc;
};

struct RMDIR3resfail {
	struct wcc_data dir_wcc;
};

struct RMDIR3res {
	nfsstat3 status;
	union {
		struct RMDIR3resok resok;
		struct RMDIR3resfail resfail;
	} u;
};

struct RENAME3args {
	struct diropargs3 from;
	struct diropargs3 to;
};

struct RENAME3resok {
	struct wcc_data fromdir_wcc;
	struct wcc_data todir_wcc;
};

struct RENAME3resfail {
	struct wcc_data fromdir_wcc;
	struct wcc_data todir_wcc;
};

struct RENAME3res {
	nfsstat3 status;
	union {
		struct RENAME3resok resok;
		struct RENAME3resfail resfail;
	} u;
};

struct LINK3args {
	struct nfs_fh3 file;
	struct diropargs3 link;
};

struct LINK3resok {
	struct post_op_attr file_attributes;
	struct wcc_data linkdir_wcc;
};

struct LINK3resfail {
	struct post_op_attr file_attributes;
	struct wcc_data linkdir_wcc;
};

struct LINK3res {
	nfsstat3 status;
	union {
		struct LINK3resok resok;
		struct LINK3resfail resfail;
	} u;
};

struct READDIR3args {
	struct nfs_fh3 dir;
	cookie3 cookie;
	cookieverf3 cookieverf;
	count3 count;
};

struct entry3 {
	fileid3 fileid;
	filename3 name;
	cookie3 cookie;
};

struct dirlist3 {
	struct entry3 *entries;
	bool eof;
};

struct READDIR3resok {
	struct post_op_attr dir_attributes;
	cookieverf3 cookieverf;
	struct dirlist3 reply;
};

struct READDIR3resfail {
	struct post_op_attr dir_attributes;
};

struct READDIR3res {
	nfsstat3 status;
	union {
		struct READDIR3resok resok;
		struct READDIR3resfail resfail;
	} u;
};

struct READDIRPLUS3args {
	struct nfs_fh3 dir;
	cookie3 cookie;
	cookieverf3 cookieverf;
	count3 dircount;
	count3 maxcount;
};

struct entryplus3 {
	fileid3 fileid;
	filename3 name;
	cookie3 cookie;
	struct post_op_attr name_attributes;
	struct post_op_fh3 name_handle;
};

struct dirlistplus3 {
	struct entryplus3 *entries;
	bool eof;
};

struct READDIRPLUS3resok {
	struct post_op_attr dir_attributes;
	cookieverf3 cookieverf;
	struct dirlistplus3 reply;
};

struct READDIRPLUS3resfail {
	struct post_op_attr dir_attributes;
};

struct READDIRPLUS3res {
	nfsstat3 status;
	union {
		struct READDIRPLUS3resok resok;
		struct READDIRPLUS3resfail resfail;
	} u;
};

struct FSSTAT3args {
	struct nfs_fh3 fsroot;
};

struct FSSTAT3resok {
	struct post_op_attr obj_attributes;
	size3 tbytes;
	size3 fbytes;
	size3 abytes;
	size3 tfiles;
	size3 ffiles;
	size3 afiles;
	uint32 invarsec;
};

struct FSSTAT3resfail {
	struct post_op_attr obj_attributes;
};

struct FSSTAT3res {
	nfsstat3 status;
	union {
		struct FSSTAT3resok resok;
		struct FSSTAT3resfail resfail;
	} u;
};

enum { FSF3_LINK = 0x0001 };

enum { FSF3_SYMLINK = 0x0002 };

enum { FSF3_HOMOGENEOUS = 0x0008 };

enum { FSF3_CANSETTIME = 0x0010 };

struct FSINFO3args {
	struct nfs_fh3 fsroot;
};

struct FSINFO3resok {
	struct post_op_attr obj_attributes;
	uint32 rtmax;
	uint32 rtpref;
	uint32 rtmult;
	uint32 wtmax;
	uint32 wtpref;
	uint32 wtmult;
	uint32 dtpref;
	size3 maxfilesize;
	struct nfstime3 time_delta;
	uint32 properties;
};

struct FSINFO3resfail {
	struct post_op_attr obj_attributes;
};

struct FSINFO3res {
	nfsstat3 status;
	union {
		struct FSINFO3resok resok;
		struct FSINFO3resfail resfail;
	} u;
};

struct PATHCONF3args {
	struct nfs_fh3 object;
};

struct PATHCONF3resok {
	struct post_op_attr obj_attributes;
	uint32 linkmax;
	uint32 name_max;
	bool no_trunc;
	bool chown_restricted;
	bool case_insensitive;
	bool case_preserving;
};

struct PATHCONF3resfail {
	struct post_op_attr obj_attributes;
};

struct PATHCONF3res {
	nfsstat3 status;
	union {
		struct PATHCONF3resok resok;
		struct PATHCONF3resfail resfail;
	} u;
};

struct COMMIT3args {
	struct nfs_fh3 file;
	offset3 offset;
	count3 count;
};

struct COMMIT3resok {
	struct wcc_data file_wcc;
	writeverf3 verf;
};

struct COMMIT3resfail {
	struct wcc_data file_wcc;
};

struct COMMIT3res {
	nfsstat3 status;
	union {
		struct COMMIT3resok resok;
		struct COMMIT3resfail resfail;
	} u;
};

enum {
	NFSPROC3_NULL = 0,
	NFSPROC3_GETATTR = 1,
	NFSPROC3_SETATTR = 2,
	NFSPROC3_LOOKUP = 3,
	NFSPROC3_ACCESS = 4,
	NFSPROC3_READLINK = 5,
	NFSPROC3_READ = 6,
	NFSPROC3_WRITE = 7,
	NFSPROC3_CREATE = 8,
	NFSPROC3_MKDIR = 9,
	NFSPROC3_SYMLINK = 10,
	NFSPROC3_MKNOD = 11,
	NFSPROC3_REMOVE = 12,
	NFSPROC3_RMDIR = 13,
	NFSPROC3_RENAME = 14,
	NFSPROC3_LINK = 15,
	NFSPROC3_READDIR = 16,
	NFSPROC3_READDIRPLUS = 17,
	NFSPROC3_FSSTAT = 18,
	NFSPROC3_FSINFO = 19,
	NFSPROC3_PATHCONF = 20,
	NFSPROC3_COMMIT = 21,
};

#define NFS3_uint64_sz                  \
	(XDR_unsigned_hyper)
#define NFS3_int64_sz                   \
	(XDR_hyper)
#define NFS3_uint32_sz                  \
	(XDR_unsigned_long)
#define NFS3_int32_sz                   \
	(XDR_long)
#define NFS3_filename3_sz               (XDR_unsigned_int)
#define NFS3_nfspath3_sz                (XDR_unsigned_int)
#define NFS3_fileid3_sz                 \
	(NFS3_uint64_sz)
#define NFS3_cookie3_sz                 \
	(NFS3_uint64_sz)
#define NFS3_cookieverf3_sz             (XDR_QUADLEN(NFS3_COOKIEVERFSIZE))
#define NFS3_createverf3_sz             (XDR_QUADLEN(NFS3_CREATEVERFSIZE))
#define NFS3_writeverf3_sz              (XDR_QUADLEN(NFS3_WRITEVERFSIZE))
#define NFS3_uid3_sz                    \
	(NFS3_uint32_sz)
#define NFS3_gid3_sz                    \
	(NFS3_uint32_sz)
#define NFS3_size3_sz                   \
	(NFS3_uint64_sz)
#define NFS3_offset3_sz                 \
	(NFS3_uint64_sz)
#define NFS3_mode3_sz                   \
	(NFS3_uint32_sz)
#define NFS3_count3_sz                  \
	(NFS3_uint32_sz)
#define NFS3_nfsstat3_sz                (XDR_int)
#define NFS3_ftype3_sz                  (XDR_int)
#define NFS3_specdata3_sz               \
	(NFS3_uint32_sz + NFS3_uint32_sz)
#define NFS3_nfs_fh3_sz                 \
	(XDR_unsigned_int + XDR_QUADLEN(NFS3_FHSIZE))
#define NFS3_nfstime3_sz                \
	(NFS3_uint32_sz + NFS3_uint32_sz)
#define NFS3_fattr3_sz                  \
	(NFS3_ftype3_sz + NFS3_mode3_sz + NFS3_uint32_sz + NFS3_uid3_sz + NFS3_gid3_sz + NFS3_size3_sz + NFS3_size3_sz + NFS3_specdata3_sz + NFS3_uint64_sz + NFS3_fileid3_sz + NFS3_nfstime3_sz + NFS3_nfstime3_sz + NFS3_nfstime3_sz)
#define NFS3_post_op_attr_sz            \
	(XDR_bool + NFS3_fattr3_sz)
#define NFS3_wcc_attr_sz                \
	(NFS3_size3_sz + NFS3_nfstime3_sz + NFS3_nfstime3_sz)
#define NFS3_pre_op_attr_sz             \
	(XDR_bool + NFS3_wcc_attr_sz)
#define NFS3_wcc_data_sz                \
	(NFS3_pre_op_attr_sz + NFS3_post_op_attr_sz)
#define NFS3_post_op_fh3_sz             \
	(XDR_bool + NFS3_nfs_fh3_sz)
#define NFS3_time_how_sz                (XDR_int)
#define NFS3_set_mode3_sz               \
	(NFS3_time_how_sz + NFS3_mode3_sz)
#define NFS3_set_uid3_sz                \
	(NFS3_time_how_sz + NFS3_uid3_sz)
#define NFS3_set_gid3_sz                \
	(NFS3_time_how_sz + NFS3_gid3_sz)
#define NFS3_set_size3_sz               \
	(NFS3_time_how_sz + NFS3_size3_sz)
#define NFS3_set_atime_sz               \
	(NFS3_time_how_sz + NFS3_nfstime3_sz)
#define NFS3_set_mtime_sz               \
	(NFS3_time_how_sz + NFS3_nfstime3_sz)
#define NFS3_sattr3_sz                  \
	(NFS3_set_mode3_sz + NFS3_set_uid3_sz + NFS3_set_gid3_sz + NFS3_set_size3_sz + NFS3_set_atime_sz + NFS3_set_mtime_sz)
#define NFS3_diropargs3_sz              \
	(NFS3_nfs_fh3_sz + NFS3_filename3_sz)
#define NFS3_GETATTR3args_sz            \
	(NFS3_nfs_fh3_sz)
#define NFS3_GETATTR3resok_sz           \
	(NFS3_fattr3_sz)
#define NFS3_GETATTR3res_sz             \
	(NFS3_nfsstat3_sz + NFS3_GETATTR3resok_sz)
#define NFS3_sattrguard3_sz             \
	(XDR_bool + NFS3_nfstime3_sz)
#define NFS3_SETATTR3args_sz            \
	(NFS3_nfs_fh3_sz + NFS3_sattr3_sz + NFS3_sattrguard3_sz)
#define NFS3_SETATTR3resok_sz           \
	(NFS3_wcc_data_sz)
#define NFS3_SETATTR3resfail_sz         \
	(NFS3_wcc_data_sz)
#define NFS3_SETATTR3res_sz             \
	(NFS3_nfsstat3_sz + NFS3_SETATTR3resok_sz)
#define NFS3_LOOKUP3args_sz             \
	(NFS3_diropargs3_sz)
#define NFS3_LOOKUP3resok_sz            \
	(NFS3_nfs_fh3_sz + NFS3_post_op_attr_sz + NFS3_post_op_attr_sz)
#define NFS3_LOOKUP3resfail_sz          \
	(NFS3_post_op_attr_sz)
#define NFS3_LOOKUP3res_sz              \
	(NFS3_nfsstat3_sz + NFS3_LOOKUP3resok_sz)
#define NFS3_ACCESS3args_sz             \
	(NFS3_nfs_fh3_sz + NFS3_uint32_sz)
#define NFS3_ACCESS3resok_sz            \
	(NFS3_post_op_attr_sz + NFS3_uint32_sz)
#define NFS3_ACCESS3resfail_sz          \
	(NFS3_post_op_attr_sz)
#define NFS3_ACCESS3res_sz              \
	(NFS3_nfsstat3_sz + NFS3_ACCESS3resok_sz)
#define NFS3_READLINK3args_sz           \
	(NFS3_nfs_fh3_sz)
#define NFS3_READLINK3resok_sz          \
	(NFS3_post_op_attr_sz + NFS3_nfspath3_sz)
#define NFS3_READLINK3resfail_sz        \
	(NFS3_post_op_attr_sz)
#define NFS3_READLINK3res_sz            \
	(NFS3_nfsstat3_sz + NFS3_READLINK3resok_sz)
#define NFS3_READ3args_sz               \
	(NFS3_nfs_fh3_sz + NFS3_offset3_sz + NFS3_count3_sz)
#define NFS3_READ3resok_sz              \
	(NFS3_post_op_attr_sz + NFS3_count3_sz + XDR_bool + XDR_unsigned_int)
#define NFS3_READ3resfail_sz            \
	(NFS3_post_op_attr_sz)
#define NFS3_READ3res_sz                \
	(NFS3_nfsstat3_sz + NFS3_READ3resok_sz)
#define NFS3_stable_how_sz              (XDR_int)
#define NFS3_WRITE3args_sz              \
	(NFS3_nfs_fh3_sz + NFS3_offset3_sz + NFS3_count3_sz + NFS3_stable_how_sz + XDR_unsigned_int)
#define NFS3_WRITE3resok_sz             \
	(NFS3_wcc_data_sz + NFS3_count3_sz + NFS3_stable_how_sz + NFS3_writeverf3_sz)
#define NFS3_WRITE3resfail_sz           \
	(NFS3_wcc_data_sz)
#define NFS3_WRITE3res_sz               \
	(NFS3_nfsstat3_sz + NFS3_WRITE3resok_sz)
#define NFS3_createmode3_sz             (XDR_int)
#define NFS3_createhow3_sz              \
	(NFS3_createmode3_sz + NFS3_sattr3_sz)
#define NFS3_CREATE3args_sz             \
	(NFS3_diropargs3_sz + NFS3_createhow3_sz)
#define NFS3_CREATE3resok_sz            \
	(NFS3_post_op_fh3_sz + NFS3_post_op_attr_sz + NFS3_wcc_data_sz)
#define NFS3_CREATE3resfail_sz          \
	(NFS3_wcc_data_sz)
#define NFS3_CREATE3res_sz              \
	(NFS3_nfsstat3_sz + NFS3_CREATE3resok_sz)
#define NFS3_MKDIR3args_sz              \
	(NFS3_diropargs3_sz + NFS3_sattr3_sz)
#define NFS3_MKDIR3resok_sz             \
	(NFS3_post_op_fh3_sz + NFS3_post_op_attr_sz + NFS3_wcc_data_sz)
#define NFS3_MKDIR3resfail_sz           \
	(NFS3_wcc_data_sz)
#define NFS3_MKDIR3res_sz               \
	(NFS3_nfsstat3_sz + NFS3_MKDIR3resok_sz)
#define NFS3_symlinkdata3_sz            \
	(NFS3_sattr3_sz + NFS3_nfspath3_sz)
#define NFS3_SYMLINK3args_sz            \
	(NFS3_diropargs3_sz + NFS3_symlinkdata3_sz)
#define NFS3_SYMLINK3resok_sz           \
	(NFS3_post_op_fh3_sz + NFS3_post_op_attr_sz + NFS3_wcc_data_sz)
#define NFS3_SYMLINK3resfail_sz         \
	(NFS3_wcc_data_sz)
#define NFS3_SYMLINK3res_sz             \
	(NFS3_nfsstat3_sz + NFS3_SYMLINK3resok_sz)
#define NFS3_devicedata3_sz             \
	(NFS3_sattr3_sz + NFS3_specdata3_sz)
#define NFS3_mknoddata3_sz              \
	(NFS3_ftype3_sz + NFS3_devicedata3_sz)
#define NFS3_MKNOD3args_sz              \
	(NFS3_diropargs3_sz + NFS3_mknoddata3_sz)
#define NFS3_MKNOD3resok_sz             \
	(NFS3_post_op_fh3_sz + NFS3_post_op_attr_sz + NFS3_wcc_data_sz)
#define NFS3_MKNOD3resfail_sz           \
	(NFS3_wcc_data_sz)
#define NFS3_MKNOD3res_sz               \
	(NFS3_nfsstat3_sz + NFS3_MKNOD3resok_sz)
#define NFS3_REMOVE3args_sz             \
	(NFS3_diropargs3_sz)
#define NFS3_REMOVE3resok_sz            \
	(NFS3_wcc_data_sz)
#define NFS3_REMOVE3resfail_sz          \
	(NFS3_wcc_data_sz)
#define NFS3_REMOVE3res_sz              \
	(NFS3_nfsstat3_sz + NFS3_REMOVE3resok_sz)
#define NFS3_RMDIR3args_sz              \
	(NFS3_diropargs3_sz)
#define NFS3_RMDIR3resok_sz             \
	(NFS3_wcc_data_sz)
#define NFS3_RMDIR3resfail_sz           \
	(NFS3_wcc_data_sz)
#define NFS3_RMDIR3res_sz               \
	(NFS3_nfsstat3_sz + NFS3_RMDIR3resok_sz)
#define NFS3_RENAME3args_sz             \
	(NFS3_diropargs3_sz + NFS3_diropargs3_sz)
#define NFS3_RENAME3resok_sz            \
	(NFS3_wcc_data_sz + NFS3_wcc_data_sz)
#define NFS3_RENAME3resfail_sz          \
	(NFS3_wcc_data_sz + NFS3_wcc_data_sz)
#define NFS3_RENAME3res_sz              \
	(NFS3_nfsstat3_sz + NFS3_RENAME3resok_sz)
#define NFS3_LINK3args_sz               \
	(NFS3_nfs_fh3_sz + NFS3_diropargs3_sz)
#define NFS3_LINK3resok_sz              \
	(NFS3_post_op_attr_sz + NFS3_wcc_data_sz)
#define NFS3_LINK3resfail_sz            \
	(NFS3_post_op_attr_sz + NFS3_wcc_data_sz)
#define NFS3_LINK3res_sz                \
	(NFS3_nfsstat3_sz + NFS3_LINK3resok_sz)
#define NFS3_READDIR3args_sz            \
	(NFS3_nfs_fh3_sz + NFS3_cookie3_sz + NFS3_cookieverf3_sz + NFS3_count3_sz)
#define NFS3_entry3_sz                  \
	(XDR_bool + NFS3_fileid3_sz + NFS3_filename3_sz + NFS3_cookie3_sz)
#define NFS3_dirlist3_sz                \
	(XDR_bool + XDR_bool)
#define NFS3_READDIR3resok_sz           \
	(NFS3_post_op_attr_sz + NFS3_cookieverf3_sz + NFS3_dirlist3_sz)
#define NFS3_READDIR3resfail_sz         \
	(NFS3_post_op_attr_sz)
#define NFS3_READDIR3res_sz             \
	(NFS3_nfsstat3_sz + NFS3_READDIR3resok_sz)
#define NFS3_READDIRPLUS3args_sz        \
	(NFS3_nfs_fh3_sz + NFS3_cookie3_sz + NFS3_cookieverf3_sz + NFS3_count3_sz + NFS3_count3_sz)
#define NFS3_entryplus3_sz              \
	(XDR_bool + NFS3_fileid3_sz + NFS3_filename3_sz + NFS3_cookie3_sz + NFS3_post_op_attr_sz + NFS3_post_op_fh3_sz)
#define NFS3_dirlistplus3_sz            \
	(XDR_bool + XDR_bool)
#define NFS3_READDIRPLUS3resok_sz       \
	(NFS3_post_op_attr_sz + NFS3_cookieverf3_sz + NFS3_dirlistplus3_sz)
#define NFS3_READDIRPLUS3resfail_sz     \
	(NFS3_post_op_attr_sz)
#define NFS3_READDIRPLUS3res_sz         \
	(NFS3_nfsstat3_sz + NFS3_READDIRPLUS3resok_sz)
#define NFS3_FSSTAT3args_sz             \
	(NFS3_nfs_fh3_sz)
#define NFS3_FSSTAT3resok_sz            \
	(NFS3_post_op_attr_sz + NFS3_size3_sz + NFS3_size3_sz + NFS3_size3_sz + NFS3_size3_sz + NFS3_size3_sz + NFS3_size3_sz + NFS3_uint32_sz)
#define NFS3_FSSTAT3resfail_sz          \
	(NFS3_post_op_attr_sz)
#define NFS3_FSSTAT3res_sz              \
	(NFS3_nfsstat3_sz + NFS3_FSSTAT3resok_sz)
#define NFS3_FSINFO3args_sz             \
	(NFS3_nfs_fh3_sz)
#define NFS3_FSINFO3resok_sz            \
	(NFS3_post_op_attr_sz + NFS3_uint32_sz + NFS3_uint32_sz + NFS3_uint32_sz + NFS3_uint32_sz + NFS3_uint32_sz + NFS3_uint32_sz + NFS3_uint32_sz + NFS3_size3_sz + NFS3_nfstime3_sz + NFS3_uint32_sz)
#define NFS3_FSINFO3resfail_sz          \
	(NFS3_post_op_attr_sz)
#define NFS3_FSINFO3res_sz              \
	(NFS3_nfsstat3_sz + NFS3_FSINFO3resok_sz)
#define NFS3_PATHCONF3args_sz           \
	(NFS3_nfs_fh3_sz)
#define NFS3_PATHCONF3resok_sz          \
	(NFS3_post_op_attr_sz + NFS3_uint32_sz + NFS3_uint32_sz + XDR_bool + XDR_bool + XDR_bool + XDR_bool)
#define NFS3_PATHCONF3resfail_sz        \
	(NFS3_post_op_attr_sz)
#define NFS3_PATHCONF3res_sz            \
	(NFS3_nfsstat3_sz + NFS3_PATHCONF3resok_sz)
#define NFS3_COMMIT3args_sz             \
	(NFS3_nfs_fh3_sz + NFS3_offset3_sz + NFS3_count3_sz)
#define NFS3_COMMIT3resok_sz            \
	(NFS3_wcc_data_sz + NFS3_writeverf3_sz)
#define NFS3_COMMIT3resfail_sz          \
	(NFS3_wcc_data_sz)
#define NFS3_COMMIT3res_sz              \
	(NFS3_nfsstat3_sz + NFS3_COMMIT3resok_sz)

#endif /* _LINUX_XDRGEN_NFS3_DEF_H */
