// SPDX-License-Identifier: GPL-2.0
// Generated by xdrgen. Manual edits will be lost.
// XDR specification file: ../../Documentation/sunrpc/xdr/nfs3.x
// XDR specification modification time: Fri Nov 28 13:37:22 2025

#include <linux/sunrpc/svc.h>

#include "nfs3xdr_gen.h"

static bool __maybe_unused
xdrgen_decode_uint64(struct xdr_stream *xdr, uint64 *ptr)
{
	return xdrgen_decode_unsigned_hyper(xdr, ptr);
}

static bool __maybe_unused
xdrgen_decode_int64(struct xdr_stream *xdr, int64 *ptr)
{
	return xdrgen_decode_hyper(xdr, ptr);
}

static bool __maybe_unused
xdrgen_decode_uint32(struct xdr_stream *xdr, uint32 *ptr)
{
	return xdrgen_decode_unsigned_long(xdr, ptr);
}

static bool __maybe_unused
xdrgen_decode_int32(struct xdr_stream *xdr, int32 *ptr)
{
	return xdrgen_decode_long(xdr, ptr);
}

static bool __maybe_unused
xdrgen_decode_filename3(struct xdr_stream *xdr, filename3 *ptr)
{
	return xdrgen_decode_string(xdr, ptr, 0);
}

static bool __maybe_unused
xdrgen_decode_nfspath3(struct xdr_stream *xdr, nfspath3 *ptr)
{
	return xdrgen_decode_string(xdr, ptr, 0);
}

static bool __maybe_unused
xdrgen_decode_fileid3(struct xdr_stream *xdr, fileid3 *ptr)
{
	return xdrgen_decode_uint64(xdr, ptr);
}

static bool __maybe_unused
xdrgen_decode_cookie3(struct xdr_stream *xdr, cookie3 *ptr)
{
	return xdrgen_decode_uint64(xdr, ptr);
}

static bool __maybe_unused
xdrgen_decode_cookieverf3(struct xdr_stream *xdr, cookieverf3 *ptr)
{
	return xdr_stream_decode_opaque_fixed(xdr, ptr, NFS3_COOKIEVERFSIZE) == 0;
}

static bool __maybe_unused
xdrgen_decode_createverf3(struct xdr_stream *xdr, createverf3 *ptr)
{
	return xdr_stream_decode_opaque_fixed(xdr, ptr, NFS3_CREATEVERFSIZE) == 0;
}

static bool __maybe_unused
xdrgen_decode_writeverf3(struct xdr_stream *xdr, writeverf3 *ptr)
{
	return xdr_stream_decode_opaque_fixed(xdr, ptr, NFS3_WRITEVERFSIZE) == 0;
}

static bool __maybe_unused
xdrgen_decode_uid3(struct xdr_stream *xdr, uid3 *ptr)
{
	return xdrgen_decode_uint32(xdr, ptr);
}

static bool __maybe_unused
xdrgen_decode_gid3(struct xdr_stream *xdr, gid3 *ptr)
{
	return xdrgen_decode_uint32(xdr, ptr);
}

static bool __maybe_unused
xdrgen_decode_size3(struct xdr_stream *xdr, size3 *ptr)
{
	return xdrgen_decode_uint64(xdr, ptr);
}

static bool __maybe_unused
xdrgen_decode_offset3(struct xdr_stream *xdr, offset3 *ptr)
{
	return xdrgen_decode_uint64(xdr, ptr);
}

static bool __maybe_unused
xdrgen_decode_mode3(struct xdr_stream *xdr, mode3 *ptr)
{
	return xdrgen_decode_uint32(xdr, ptr);
}

static bool __maybe_unused
xdrgen_decode_count3(struct xdr_stream *xdr, count3 *ptr)
{
	return xdrgen_decode_uint32(xdr, ptr);
}

static bool __maybe_unused
xdrgen_decode_nfsstat3(struct xdr_stream *xdr, nfsstat3 *ptr)
{
	return xdr_stream_decode_be32(xdr, ptr) == 0;
}

static bool __maybe_unused
xdrgen_decode_ftype3(struct xdr_stream *xdr, ftype3 *ptr)
{
	u32 val;

	if (xdr_stream_decode_u32(xdr, &val) < 0)
		return false;
	*ptr = val;
	return true;
}

static bool __maybe_unused
xdrgen_decode_specdata3(struct xdr_stream *xdr, struct specdata3 *ptr)
{
	if (!xdrgen_decode_uint32(xdr, &ptr->specdata1))
		return false;
	if (!xdrgen_decode_uint32(xdr, &ptr->specdata2))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_nfs_fh3(struct xdr_stream *xdr, struct nfs_fh3 *ptr)
{
	if (!xdrgen_decode_opaque(xdr, &ptr->data, NFS3_FHSIZE))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_nfstime3(struct xdr_stream *xdr, struct nfstime3 *ptr)
{
	if (!xdrgen_decode_uint32(xdr, &ptr->seconds))
		return false;
	if (!xdrgen_decode_uint32(xdr, &ptr->nseconds))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_fattr3(struct xdr_stream *xdr, struct fattr3 *ptr)
{
	if (!xdrgen_decode_ftype3(xdr, &ptr->type))
		return false;
	if (!xdrgen_decode_mode3(xdr, &ptr->mode))
		return false;
	if (!xdrgen_decode_uint32(xdr, &ptr->nlink))
		return false;
	if (!xdrgen_decode_uid3(xdr, &ptr->uid))
		return false;
	if (!xdrgen_decode_gid3(xdr, &ptr->gid))
		return false;
	if (!xdrgen_decode_size3(xdr, &ptr->size))
		return false;
	if (!xdrgen_decode_size3(xdr, &ptr->used))
		return false;
	if (!xdrgen_decode_specdata3(xdr, &ptr->rdev))
		return false;
	if (!xdrgen_decode_uint64(xdr, &ptr->fsid))
		return false;
	if (!xdrgen_decode_fileid3(xdr, &ptr->fileid))
		return false;
	if (!xdrgen_decode_nfstime3(xdr, &ptr->atime))
		return false;
	if (!xdrgen_decode_nfstime3(xdr, &ptr->mtime))
		return false;
	if (!xdrgen_decode_nfstime3(xdr, &ptr->ctime))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_post_op_attr(struct xdr_stream *xdr, struct post_op_attr *ptr)
{
	if (!xdrgen_decode_bool(xdr, &ptr->attributes_follow))
		return false;
	if (ptr->attributes_follow) {
		if (!xdrgen_decode_fattr3(xdr, &ptr->u.attributes))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_wcc_attr(struct xdr_stream *xdr, struct wcc_attr *ptr)
{
	if (!xdrgen_decode_size3(xdr, &ptr->size))
		return false;
	if (!xdrgen_decode_nfstime3(xdr, &ptr->mtime))
		return false;
	if (!xdrgen_decode_nfstime3(xdr, &ptr->ctime))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_pre_op_attr(struct xdr_stream *xdr, struct pre_op_attr *ptr)
{
	if (!xdrgen_decode_bool(xdr, &ptr->attributes_follow))
		return false;
	if (ptr->attributes_follow) {
		if (!xdrgen_decode_wcc_attr(xdr, &ptr->u.attributes))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_wcc_data(struct xdr_stream *xdr, struct wcc_data *ptr)
{
	if (!xdrgen_decode_pre_op_attr(xdr, &ptr->before))
		return false;
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->after))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_post_op_fh3(struct xdr_stream *xdr, struct post_op_fh3 *ptr)
{
	if (!xdrgen_decode_bool(xdr, &ptr->handle_follows))
		return false;
	if (ptr->handle_follows) {
		if (!xdrgen_decode_nfs_fh3(xdr, &ptr->u.handle))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_time_how(struct xdr_stream *xdr, time_how *ptr)
{
	u32 val;

	if (xdr_stream_decode_u32(xdr, &val) < 0)
		return false;
	*ptr = val;
	return true;
}

static bool __maybe_unused
xdrgen_decode_set_mode3(struct xdr_stream *xdr, struct set_mode3 *ptr)
{
	if (!xdrgen_decode_bool(xdr, &ptr->set_it))
		return false;
	if (ptr->set_it) {
		if (!xdrgen_decode_mode3(xdr, &ptr->u.mode))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_set_uid3(struct xdr_stream *xdr, struct set_uid3 *ptr)
{
	if (!xdrgen_decode_bool(xdr, &ptr->set_it))
		return false;
	if (ptr->set_it) {
		if (!xdrgen_decode_uid3(xdr, &ptr->u.uid))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_set_gid3(struct xdr_stream *xdr, struct set_gid3 *ptr)
{
	if (!xdrgen_decode_bool(xdr, &ptr->set_it))
		return false;
	if (ptr->set_it) {
		if (!xdrgen_decode_gid3(xdr, &ptr->u.gid))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_set_size3(struct xdr_stream *xdr, struct set_size3 *ptr)
{
	if (!xdrgen_decode_bool(xdr, &ptr->set_it))
		return false;
	if (ptr->set_it) {
		if (!xdrgen_decode_size3(xdr, &ptr->u.size))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_set_atime(struct xdr_stream *xdr, struct set_atime *ptr)
{
	if (!xdrgen_decode_time_how(xdr, &ptr->set_it))
		return false;
	switch (ptr->set_it) {
	case SET_TO_CLIENT_TIME:
		if (!xdrgen_decode_nfstime3(xdr, &ptr->u.atime))
			return false;
		break;
	default:
		break;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_set_mtime(struct xdr_stream *xdr, struct set_mtime *ptr)
{
	if (!xdrgen_decode_time_how(xdr, &ptr->set_it))
		return false;
	switch (ptr->set_it) {
	case SET_TO_CLIENT_TIME:
		if (!xdrgen_decode_nfstime3(xdr, &ptr->u.mtime))
			return false;
		break;
	default:
		break;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_sattr3(struct xdr_stream *xdr, struct sattr3 *ptr)
{
	if (!xdrgen_decode_set_mode3(xdr, &ptr->mode))
		return false;
	if (!xdrgen_decode_set_uid3(xdr, &ptr->uid))
		return false;
	if (!xdrgen_decode_set_gid3(xdr, &ptr->gid))
		return false;
	if (!xdrgen_decode_set_size3(xdr, &ptr->size))
		return false;
	if (!xdrgen_decode_set_atime(xdr, &ptr->atime))
		return false;
	if (!xdrgen_decode_set_mtime(xdr, &ptr->mtime))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_diropargs3(struct xdr_stream *xdr, struct diropargs3 *ptr)
{
	if (!xdrgen_decode_nfs_fh3(xdr, &ptr->dir))
		return false;
	if (!xdrgen_decode_filename3(xdr, &ptr->name))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_GETATTR3args(struct xdr_stream *xdr, struct GETATTR3args *ptr)
{
	if (!xdrgen_decode_nfs_fh3(xdr, &ptr->object))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_GETATTR3resok(struct xdr_stream *xdr, struct GETATTR3resok *ptr)
{
	if (!xdrgen_decode_fattr3(xdr, &ptr->obj_attributes))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_GETATTR3res(struct xdr_stream *xdr, struct GETATTR3res *ptr)
{
	if (!xdrgen_decode_nfsstat3(xdr, &ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_decode_GETATTR3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		break;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_sattrguard3(struct xdr_stream *xdr, struct sattrguard3 *ptr)
{
	if (!xdrgen_decode_bool(xdr, &ptr->check))
		return false;
	if (ptr->check) {
		if (!xdrgen_decode_nfstime3(xdr, &ptr->u.obj_ctime))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_SETATTR3args(struct xdr_stream *xdr, struct SETATTR3args *ptr)
{
	if (!xdrgen_decode_nfs_fh3(xdr, &ptr->object))
		return false;
	if (!xdrgen_decode_sattr3(xdr, &ptr->new_attributes))
		return false;
	if (!xdrgen_decode_sattrguard3(xdr, &ptr->guard))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_SETATTR3resok(struct xdr_stream *xdr, struct SETATTR3resok *ptr)
{
	if (!xdrgen_decode_wcc_data(xdr, &ptr->obj_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_SETATTR3resfail(struct xdr_stream *xdr, struct SETATTR3resfail *ptr)
{
	if (!xdrgen_decode_wcc_data(xdr, &ptr->obj_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_SETATTR3res(struct xdr_stream *xdr, struct SETATTR3res *ptr)
{
	if (!xdrgen_decode_nfsstat3(xdr, &ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_decode_SETATTR3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_decode_SETATTR3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_LOOKUP3args(struct xdr_stream *xdr, struct LOOKUP3args *ptr)
{
	if (!xdrgen_decode_diropargs3(xdr, &ptr->what))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_LOOKUP3resok(struct xdr_stream *xdr, struct LOOKUP3resok *ptr)
{
	if (!xdrgen_decode_nfs_fh3(xdr, &ptr->object))
		return false;
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->obj_attributes))
		return false;
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->dir_attributes))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_LOOKUP3resfail(struct xdr_stream *xdr, struct LOOKUP3resfail *ptr)
{
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->dir_attributes))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_LOOKUP3res(struct xdr_stream *xdr, struct LOOKUP3res *ptr)
{
	if (!xdrgen_decode_nfsstat3(xdr, &ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_decode_LOOKUP3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_decode_LOOKUP3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_ACCESS3args(struct xdr_stream *xdr, struct ACCESS3args *ptr)
{
	if (!xdrgen_decode_nfs_fh3(xdr, &ptr->object))
		return false;
	if (!xdrgen_decode_uint32(xdr, &ptr->access))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_ACCESS3resok(struct xdr_stream *xdr, struct ACCESS3resok *ptr)
{
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->obj_attributes))
		return false;
	if (!xdrgen_decode_uint32(xdr, &ptr->access))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_ACCESS3resfail(struct xdr_stream *xdr, struct ACCESS3resfail *ptr)
{
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->obj_attributes))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_ACCESS3res(struct xdr_stream *xdr, struct ACCESS3res *ptr)
{
	if (!xdrgen_decode_nfsstat3(xdr, &ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_decode_ACCESS3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_decode_ACCESS3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_READLINK3args(struct xdr_stream *xdr, struct READLINK3args *ptr)
{
	if (!xdrgen_decode_nfs_fh3(xdr, &ptr->symlink))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_READLINK3resok(struct xdr_stream *xdr, struct READLINK3resok *ptr)
{
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->symlink_attributes))
		return false;
	if (!xdrgen_decode_nfspath3(xdr, &ptr->data))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_READLINK3resfail(struct xdr_stream *xdr, struct READLINK3resfail *ptr)
{
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->symlink_attributes))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_READLINK3res(struct xdr_stream *xdr, struct READLINK3res *ptr)
{
	if (!xdrgen_decode_nfsstat3(xdr, &ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_decode_READLINK3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_decode_READLINK3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_READ3args(struct xdr_stream *xdr, struct READ3args *ptr)
{
	if (!xdrgen_decode_nfs_fh3(xdr, &ptr->file))
		return false;
	if (!xdrgen_decode_offset3(xdr, &ptr->offset))
		return false;
	if (!xdrgen_decode_count3(xdr, &ptr->count))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_READ3resok(struct xdr_stream *xdr, struct READ3resok *ptr)
{
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->file_attributes))
		return false;
	if (!xdrgen_decode_count3(xdr, &ptr->count))
		return false;
	if (!xdrgen_decode_bool(xdr, &ptr->eof))
		return false;
	if (!xdrgen_decode_opaque(xdr, &ptr->data, 0))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_READ3resfail(struct xdr_stream *xdr, struct READ3resfail *ptr)
{
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->file_attributes))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_READ3res(struct xdr_stream *xdr, struct READ3res *ptr)
{
	if (!xdrgen_decode_nfsstat3(xdr, &ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_decode_READ3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_decode_READ3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_stable_how(struct xdr_stream *xdr, stable_how *ptr)
{
	u32 val;

	if (xdr_stream_decode_u32(xdr, &val) < 0)
		return false;
	*ptr = val;
	return true;
}

static bool __maybe_unused
xdrgen_decode_WRITE3args(struct xdr_stream *xdr, struct WRITE3args *ptr)
{
	if (!xdrgen_decode_nfs_fh3(xdr, &ptr->file))
		return false;
	if (!xdrgen_decode_offset3(xdr, &ptr->offset))
		return false;
	if (!xdrgen_decode_count3(xdr, &ptr->count))
		return false;
	if (!xdrgen_decode_stable_how(xdr, &ptr->stable))
		return false;
	if (!xdrgen_decode_opaque(xdr, &ptr->data, 0))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_WRITE3resok(struct xdr_stream *xdr, struct WRITE3resok *ptr)
{
	if (!xdrgen_decode_wcc_data(xdr, &ptr->file_wcc))
		return false;
	if (!xdrgen_decode_count3(xdr, &ptr->count))
		return false;
	if (!xdrgen_decode_stable_how(xdr, &ptr->committed))
		return false;
	if (!xdrgen_decode_writeverf3(xdr, &ptr->verf))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_WRITE3resfail(struct xdr_stream *xdr, struct WRITE3resfail *ptr)
{
	if (!xdrgen_decode_wcc_data(xdr, &ptr->file_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_WRITE3res(struct xdr_stream *xdr, struct WRITE3res *ptr)
{
	if (!xdrgen_decode_nfsstat3(xdr, &ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_decode_WRITE3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_decode_WRITE3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_createmode3(struct xdr_stream *xdr, createmode3 *ptr)
{
	u32 val;

	if (xdr_stream_decode_u32(xdr, &val) < 0)
		return false;
	*ptr = val;
	return true;
}

static bool __maybe_unused
xdrgen_decode_createhow3(struct xdr_stream *xdr, struct createhow3 *ptr)
{
	if (!xdrgen_decode_createmode3(xdr, &ptr->mode))
		return false;
	switch (ptr->mode) {
	case UNCHECKED:
	case GUARDED:
		if (!xdrgen_decode_sattr3(xdr, &ptr->u.obj_attributes))
			return false;
		break;
	case EXCLUSIVE:
		if (!xdrgen_decode_createverf3(xdr, &ptr->u.verf))
			return false;
		break;
	default:
		break;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_CREATE3args(struct xdr_stream *xdr, struct CREATE3args *ptr)
{
	if (!xdrgen_decode_diropargs3(xdr, &ptr->where))
		return false;
	if (!xdrgen_decode_createhow3(xdr, &ptr->how))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_CREATE3resok(struct xdr_stream *xdr, struct CREATE3resok *ptr)
{
	if (!xdrgen_decode_post_op_fh3(xdr, &ptr->obj))
		return false;
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->obj_attributes))
		return false;
	if (!xdrgen_decode_wcc_data(xdr, &ptr->dir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_CREATE3resfail(struct xdr_stream *xdr, struct CREATE3resfail *ptr)
{
	if (!xdrgen_decode_wcc_data(xdr, &ptr->dir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_CREATE3res(struct xdr_stream *xdr, struct CREATE3res *ptr)
{
	if (!xdrgen_decode_nfsstat3(xdr, &ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_decode_CREATE3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_decode_CREATE3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_MKDIR3args(struct xdr_stream *xdr, struct MKDIR3args *ptr)
{
	if (!xdrgen_decode_diropargs3(xdr, &ptr->where))
		return false;
	if (!xdrgen_decode_sattr3(xdr, &ptr->attributes))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_MKDIR3resok(struct xdr_stream *xdr, struct MKDIR3resok *ptr)
{
	if (!xdrgen_decode_post_op_fh3(xdr, &ptr->obj))
		return false;
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->obj_attributes))
		return false;
	if (!xdrgen_decode_wcc_data(xdr, &ptr->dir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_MKDIR3resfail(struct xdr_stream *xdr, struct MKDIR3resfail *ptr)
{
	if (!xdrgen_decode_wcc_data(xdr, &ptr->dir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_MKDIR3res(struct xdr_stream *xdr, struct MKDIR3res *ptr)
{
	if (!xdrgen_decode_nfsstat3(xdr, &ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_decode_MKDIR3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_decode_MKDIR3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_symlinkdata3(struct xdr_stream *xdr, struct symlinkdata3 *ptr)
{
	if (!xdrgen_decode_sattr3(xdr, &ptr->symlink_attributes))
		return false;
	if (!xdrgen_decode_nfspath3(xdr, &ptr->symlink_data))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_SYMLINK3args(struct xdr_stream *xdr, struct SYMLINK3args *ptr)
{
	if (!xdrgen_decode_diropargs3(xdr, &ptr->where))
		return false;
	if (!xdrgen_decode_symlinkdata3(xdr, &ptr->symlink))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_SYMLINK3resok(struct xdr_stream *xdr, struct SYMLINK3resok *ptr)
{
	if (!xdrgen_decode_post_op_fh3(xdr, &ptr->obj))
		return false;
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->obj_attributes))
		return false;
	if (!xdrgen_decode_wcc_data(xdr, &ptr->dir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_SYMLINK3resfail(struct xdr_stream *xdr, struct SYMLINK3resfail *ptr)
{
	if (!xdrgen_decode_wcc_data(xdr, &ptr->dir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_SYMLINK3res(struct xdr_stream *xdr, struct SYMLINK3res *ptr)
{
	if (!xdrgen_decode_nfsstat3(xdr, &ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_decode_SYMLINK3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_decode_SYMLINK3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_devicedata3(struct xdr_stream *xdr, struct devicedata3 *ptr)
{
	if (!xdrgen_decode_sattr3(xdr, &ptr->dev_attributes))
		return false;
	if (!xdrgen_decode_specdata3(xdr, &ptr->spec))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_mknoddata3(struct xdr_stream *xdr, struct mknoddata3 *ptr)
{
	if (!xdrgen_decode_ftype3(xdr, &ptr->type))
		return false;
	switch (ptr->type) {
	case NF3CHR:
	case NF3BLK:
		if (!xdrgen_decode_devicedata3(xdr, &ptr->u.device))
			return false;
		break;
	case NF3SOCK:
	case NF3FIFO:
		if (!xdrgen_decode_sattr3(xdr, &ptr->u.pipe_attributes))
			return false;
		break;
	default:
		break;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_MKNOD3args(struct xdr_stream *xdr, struct MKNOD3args *ptr)
{
	if (!xdrgen_decode_diropargs3(xdr, &ptr->where))
		return false;
	if (!xdrgen_decode_mknoddata3(xdr, &ptr->what))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_MKNOD3resok(struct xdr_stream *xdr, struct MKNOD3resok *ptr)
{
	if (!xdrgen_decode_post_op_fh3(xdr, &ptr->obj))
		return false;
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->obj_attributes))
		return false;
	if (!xdrgen_decode_wcc_data(xdr, &ptr->dir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_MKNOD3resfail(struct xdr_stream *xdr, struct MKNOD3resfail *ptr)
{
	if (!xdrgen_decode_wcc_data(xdr, &ptr->dir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_MKNOD3res(struct xdr_stream *xdr, struct MKNOD3res *ptr)
{
	if (!xdrgen_decode_nfsstat3(xdr, &ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_decode_MKNOD3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_decode_MKNOD3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_REMOVE3args(struct xdr_stream *xdr, struct REMOVE3args *ptr)
{
	if (!xdrgen_decode_diropargs3(xdr, &ptr->object))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_REMOVE3resok(struct xdr_stream *xdr, struct REMOVE3resok *ptr)
{
	if (!xdrgen_decode_wcc_data(xdr, &ptr->dir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_REMOVE3resfail(struct xdr_stream *xdr, struct REMOVE3resfail *ptr)
{
	if (!xdrgen_decode_wcc_data(xdr, &ptr->dir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_REMOVE3res(struct xdr_stream *xdr, struct REMOVE3res *ptr)
{
	if (!xdrgen_decode_nfsstat3(xdr, &ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_decode_REMOVE3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_decode_REMOVE3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_RMDIR3args(struct xdr_stream *xdr, struct RMDIR3args *ptr)
{
	if (!xdrgen_decode_diropargs3(xdr, &ptr->object))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_RMDIR3resok(struct xdr_stream *xdr, struct RMDIR3resok *ptr)
{
	if (!xdrgen_decode_wcc_data(xdr, &ptr->dir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_RMDIR3resfail(struct xdr_stream *xdr, struct RMDIR3resfail *ptr)
{
	if (!xdrgen_decode_wcc_data(xdr, &ptr->dir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_RMDIR3res(struct xdr_stream *xdr, struct RMDIR3res *ptr)
{
	if (!xdrgen_decode_nfsstat3(xdr, &ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_decode_RMDIR3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_decode_RMDIR3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_RENAME3args(struct xdr_stream *xdr, struct RENAME3args *ptr)
{
	if (!xdrgen_decode_diropargs3(xdr, &ptr->from))
		return false;
	if (!xdrgen_decode_diropargs3(xdr, &ptr->to))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_RENAME3resok(struct xdr_stream *xdr, struct RENAME3resok *ptr)
{
	if (!xdrgen_decode_wcc_data(xdr, &ptr->fromdir_wcc))
		return false;
	if (!xdrgen_decode_wcc_data(xdr, &ptr->todir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_RENAME3resfail(struct xdr_stream *xdr, struct RENAME3resfail *ptr)
{
	if (!xdrgen_decode_wcc_data(xdr, &ptr->fromdir_wcc))
		return false;
	if (!xdrgen_decode_wcc_data(xdr, &ptr->todir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_RENAME3res(struct xdr_stream *xdr, struct RENAME3res *ptr)
{
	if (!xdrgen_decode_nfsstat3(xdr, &ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_decode_RENAME3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_decode_RENAME3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_LINK3args(struct xdr_stream *xdr, struct LINK3args *ptr)
{
	if (!xdrgen_decode_nfs_fh3(xdr, &ptr->file))
		return false;
	if (!xdrgen_decode_diropargs3(xdr, &ptr->link))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_LINK3resok(struct xdr_stream *xdr, struct LINK3resok *ptr)
{
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->file_attributes))
		return false;
	if (!xdrgen_decode_wcc_data(xdr, &ptr->linkdir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_LINK3resfail(struct xdr_stream *xdr, struct LINK3resfail *ptr)
{
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->file_attributes))
		return false;
	if (!xdrgen_decode_wcc_data(xdr, &ptr->linkdir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_LINK3res(struct xdr_stream *xdr, struct LINK3res *ptr)
{
	if (!xdrgen_decode_nfsstat3(xdr, &ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_decode_LINK3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_decode_LINK3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_READDIR3args(struct xdr_stream *xdr, struct READDIR3args *ptr)
{
	if (!xdrgen_decode_nfs_fh3(xdr, &ptr->dir))
		return false;
	if (!xdrgen_decode_cookie3(xdr, &ptr->cookie))
		return false;
	if (!xdrgen_decode_cookieverf3(xdr, &ptr->cookieverf))
		return false;
	if (!xdrgen_decode_count3(xdr, &ptr->count))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_entry3(struct xdr_stream *xdr, struct entry3 *ptr)
{
	bool opted;

	if (!xdrgen_decode_bool(xdr, &opted))
		return false;
	if (!opted)
		return true;

	if (!xdrgen_decode_fileid3(xdr, &ptr->fileid))
		return false;
	if (!xdrgen_decode_filename3(xdr, &ptr->name))
		return false;
	if (!xdrgen_decode_cookie3(xdr, &ptr->cookie))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_dirlist3(struct xdr_stream *xdr, struct dirlist3 *ptr)
{
	if (!xdrgen_decode_entry3(xdr, ptr->entries))
		return false;
	if (!xdrgen_decode_bool(xdr, &ptr->eof))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_READDIR3resok(struct xdr_stream *xdr, struct READDIR3resok *ptr)
{
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->dir_attributes))
		return false;
	if (!xdrgen_decode_cookieverf3(xdr, &ptr->cookieverf))
		return false;
	if (!xdrgen_decode_dirlist3(xdr, &ptr->reply))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_READDIR3resfail(struct xdr_stream *xdr, struct READDIR3resfail *ptr)
{
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->dir_attributes))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_READDIR3res(struct xdr_stream *xdr, struct READDIR3res *ptr)
{
	if (!xdrgen_decode_nfsstat3(xdr, &ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_decode_READDIR3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_decode_READDIR3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_READDIRPLUS3args(struct xdr_stream *xdr, struct READDIRPLUS3args *ptr)
{
	if (!xdrgen_decode_nfs_fh3(xdr, &ptr->dir))
		return false;
	if (!xdrgen_decode_cookie3(xdr, &ptr->cookie))
		return false;
	if (!xdrgen_decode_cookieverf3(xdr, &ptr->cookieverf))
		return false;
	if (!xdrgen_decode_count3(xdr, &ptr->dircount))
		return false;
	if (!xdrgen_decode_count3(xdr, &ptr->maxcount))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_entryplus3(struct xdr_stream *xdr, struct entryplus3 *ptr)
{
	bool opted;

	if (!xdrgen_decode_bool(xdr, &opted))
		return false;
	if (!opted)
		return true;

	if (!xdrgen_decode_fileid3(xdr, &ptr->fileid))
		return false;
	if (!xdrgen_decode_filename3(xdr, &ptr->name))
		return false;
	if (!xdrgen_decode_cookie3(xdr, &ptr->cookie))
		return false;
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->name_attributes))
		return false;
	if (!xdrgen_decode_post_op_fh3(xdr, &ptr->name_handle))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_dirlistplus3(struct xdr_stream *xdr, struct dirlistplus3 *ptr)
{
	if (!xdrgen_decode_entryplus3(xdr, ptr->entries))
		return false;
	if (!xdrgen_decode_bool(xdr, &ptr->eof))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_READDIRPLUS3resok(struct xdr_stream *xdr, struct READDIRPLUS3resok *ptr)
{
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->dir_attributes))
		return false;
	if (!xdrgen_decode_cookieverf3(xdr, &ptr->cookieverf))
		return false;
	if (!xdrgen_decode_dirlistplus3(xdr, &ptr->reply))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_READDIRPLUS3resfail(struct xdr_stream *xdr, struct READDIRPLUS3resfail *ptr)
{
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->dir_attributes))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_READDIRPLUS3res(struct xdr_stream *xdr, struct READDIRPLUS3res *ptr)
{
	if (!xdrgen_decode_nfsstat3(xdr, &ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_decode_READDIRPLUS3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_decode_READDIRPLUS3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_FSSTAT3args(struct xdr_stream *xdr, struct FSSTAT3args *ptr)
{
	if (!xdrgen_decode_nfs_fh3(xdr, &ptr->fsroot))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_FSSTAT3resok(struct xdr_stream *xdr, struct FSSTAT3resok *ptr)
{
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->obj_attributes))
		return false;
	if (!xdrgen_decode_size3(xdr, &ptr->tbytes))
		return false;
	if (!xdrgen_decode_size3(xdr, &ptr->fbytes))
		return false;
	if (!xdrgen_decode_size3(xdr, &ptr->abytes))
		return false;
	if (!xdrgen_decode_size3(xdr, &ptr->tfiles))
		return false;
	if (!xdrgen_decode_size3(xdr, &ptr->ffiles))
		return false;
	if (!xdrgen_decode_size3(xdr, &ptr->afiles))
		return false;
	if (!xdrgen_decode_uint32(xdr, &ptr->invarsec))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_FSSTAT3resfail(struct xdr_stream *xdr, struct FSSTAT3resfail *ptr)
{
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->obj_attributes))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_FSSTAT3res(struct xdr_stream *xdr, struct FSSTAT3res *ptr)
{
	if (!xdrgen_decode_nfsstat3(xdr, &ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_decode_FSSTAT3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_decode_FSSTAT3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_FSINFO3args(struct xdr_stream *xdr, struct FSINFO3args *ptr)
{
	if (!xdrgen_decode_nfs_fh3(xdr, &ptr->fsroot))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_FSINFO3resok(struct xdr_stream *xdr, struct FSINFO3resok *ptr)
{
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->obj_attributes))
		return false;
	if (!xdrgen_decode_uint32(xdr, &ptr->rtmax))
		return false;
	if (!xdrgen_decode_uint32(xdr, &ptr->rtpref))
		return false;
	if (!xdrgen_decode_uint32(xdr, &ptr->rtmult))
		return false;
	if (!xdrgen_decode_uint32(xdr, &ptr->wtmax))
		return false;
	if (!xdrgen_decode_uint32(xdr, &ptr->wtpref))
		return false;
	if (!xdrgen_decode_uint32(xdr, &ptr->wtmult))
		return false;
	if (!xdrgen_decode_uint32(xdr, &ptr->dtpref))
		return false;
	if (!xdrgen_decode_size3(xdr, &ptr->maxfilesize))
		return false;
	if (!xdrgen_decode_nfstime3(xdr, &ptr->time_delta))
		return false;
	if (!xdrgen_decode_uint32(xdr, &ptr->properties))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_FSINFO3resfail(struct xdr_stream *xdr, struct FSINFO3resfail *ptr)
{
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->obj_attributes))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_FSINFO3res(struct xdr_stream *xdr, struct FSINFO3res *ptr)
{
	if (!xdrgen_decode_nfsstat3(xdr, &ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_decode_FSINFO3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_decode_FSINFO3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_PATHCONF3args(struct xdr_stream *xdr, struct PATHCONF3args *ptr)
{
	if (!xdrgen_decode_nfs_fh3(xdr, &ptr->object))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_PATHCONF3resok(struct xdr_stream *xdr, struct PATHCONF3resok *ptr)
{
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->obj_attributes))
		return false;
	if (!xdrgen_decode_uint32(xdr, &ptr->linkmax))
		return false;
	if (!xdrgen_decode_uint32(xdr, &ptr->name_max))
		return false;
	if (!xdrgen_decode_bool(xdr, &ptr->no_trunc))
		return false;
	if (!xdrgen_decode_bool(xdr, &ptr->chown_restricted))
		return false;
	if (!xdrgen_decode_bool(xdr, &ptr->case_insensitive))
		return false;
	if (!xdrgen_decode_bool(xdr, &ptr->case_preserving))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_PATHCONF3resfail(struct xdr_stream *xdr, struct PATHCONF3resfail *ptr)
{
	if (!xdrgen_decode_post_op_attr(xdr, &ptr->obj_attributes))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_PATHCONF3res(struct xdr_stream *xdr, struct PATHCONF3res *ptr)
{
	if (!xdrgen_decode_nfsstat3(xdr, &ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_decode_PATHCONF3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_decode_PATHCONF3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_decode_COMMIT3args(struct xdr_stream *xdr, struct COMMIT3args *ptr)
{
	if (!xdrgen_decode_nfs_fh3(xdr, &ptr->file))
		return false;
	if (!xdrgen_decode_offset3(xdr, &ptr->offset))
		return false;
	if (!xdrgen_decode_count3(xdr, &ptr->count))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_COMMIT3resok(struct xdr_stream *xdr, struct COMMIT3resok *ptr)
{
	if (!xdrgen_decode_wcc_data(xdr, &ptr->file_wcc))
		return false;
	if (!xdrgen_decode_writeverf3(xdr, &ptr->verf))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_COMMIT3resfail(struct xdr_stream *xdr, struct COMMIT3resfail *ptr)
{
	if (!xdrgen_decode_wcc_data(xdr, &ptr->file_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_decode_COMMIT3res(struct xdr_stream *xdr, struct COMMIT3res *ptr)
{
	if (!xdrgen_decode_nfsstat3(xdr, &ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_decode_COMMIT3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_decode_COMMIT3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

/**
 * nfs_svc_decode_void - Decode a void argument
 * @rqstp: RPC transaction context
 * @xdr: source XDR data stream
 *
 * Return values:
 *   %true: procedure arguments decoded successfully
 *   %false: decode failed
 */
bool nfs_svc_decode_void(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	return xdrgen_decode_void(xdr);
}

/**
 * nfs_svc_decode_GETATTR3args - Decode a GETATTR3args argument
 * @rqstp: RPC transaction context
 * @xdr: source XDR data stream
 *
 * Return values:
 *   %true: procedure arguments decoded successfully
 *   %false: decode failed
 */
bool nfs_svc_decode_GETATTR3args(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct GETATTR3args *argp = rqstp->rq_argp;

	return xdrgen_decode_GETATTR3args(xdr, argp);
}

/**
 * nfs_svc_decode_SETATTR3args - Decode a SETATTR3args argument
 * @rqstp: RPC transaction context
 * @xdr: source XDR data stream
 *
 * Return values:
 *   %true: procedure arguments decoded successfully
 *   %false: decode failed
 */
bool nfs_svc_decode_SETATTR3args(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct SETATTR3args *argp = rqstp->rq_argp;

	return xdrgen_decode_SETATTR3args(xdr, argp);
}

/**
 * nfs_svc_decode_LOOKUP3args - Decode a LOOKUP3args argument
 * @rqstp: RPC transaction context
 * @xdr: source XDR data stream
 *
 * Return values:
 *   %true: procedure arguments decoded successfully
 *   %false: decode failed
 */
bool nfs_svc_decode_LOOKUP3args(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct LOOKUP3args *argp = rqstp->rq_argp;

	return xdrgen_decode_LOOKUP3args(xdr, argp);
}

/**
 * nfs_svc_decode_ACCESS3args - Decode a ACCESS3args argument
 * @rqstp: RPC transaction context
 * @xdr: source XDR data stream
 *
 * Return values:
 *   %true: procedure arguments decoded successfully
 *   %false: decode failed
 */
bool nfs_svc_decode_ACCESS3args(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct ACCESS3args *argp = rqstp->rq_argp;

	return xdrgen_decode_ACCESS3args(xdr, argp);
}

/**
 * nfs_svc_decode_READLINK3args - Decode a READLINK3args argument
 * @rqstp: RPC transaction context
 * @xdr: source XDR data stream
 *
 * Return values:
 *   %true: procedure arguments decoded successfully
 *   %false: decode failed
 */
bool nfs_svc_decode_READLINK3args(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct READLINK3args *argp = rqstp->rq_argp;

	return xdrgen_decode_READLINK3args(xdr, argp);
}

/**
 * nfs_svc_decode_READ3args - Decode a READ3args argument
 * @rqstp: RPC transaction context
 * @xdr: source XDR data stream
 *
 * Return values:
 *   %true: procedure arguments decoded successfully
 *   %false: decode failed
 */
bool nfs_svc_decode_READ3args(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct READ3args *argp = rqstp->rq_argp;

	return xdrgen_decode_READ3args(xdr, argp);
}

/**
 * nfs_svc_decode_WRITE3args - Decode a WRITE3args argument
 * @rqstp: RPC transaction context
 * @xdr: source XDR data stream
 *
 * Return values:
 *   %true: procedure arguments decoded successfully
 *   %false: decode failed
 */
bool nfs_svc_decode_WRITE3args(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct WRITE3args *argp = rqstp->rq_argp;

	return xdrgen_decode_WRITE3args(xdr, argp);
}

/**
 * nfs_svc_decode_CREATE3args - Decode a CREATE3args argument
 * @rqstp: RPC transaction context
 * @xdr: source XDR data stream
 *
 * Return values:
 *   %true: procedure arguments decoded successfully
 *   %false: decode failed
 */
bool nfs_svc_decode_CREATE3args(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct CREATE3args *argp = rqstp->rq_argp;

	return xdrgen_decode_CREATE3args(xdr, argp);
}

/**
 * nfs_svc_decode_MKDIR3args - Decode a MKDIR3args argument
 * @rqstp: RPC transaction context
 * @xdr: source XDR data stream
 *
 * Return values:
 *   %true: procedure arguments decoded successfully
 *   %false: decode failed
 */
bool nfs_svc_decode_MKDIR3args(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct MKDIR3args *argp = rqstp->rq_argp;

	return xdrgen_decode_MKDIR3args(xdr, argp);
}

/**
 * nfs_svc_decode_SYMLINK3args - Decode a SYMLINK3args argument
 * @rqstp: RPC transaction context
 * @xdr: source XDR data stream
 *
 * Return values:
 *   %true: procedure arguments decoded successfully
 *   %false: decode failed
 */
bool nfs_svc_decode_SYMLINK3args(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct SYMLINK3args *argp = rqstp->rq_argp;

	return xdrgen_decode_SYMLINK3args(xdr, argp);
}

/**
 * nfs_svc_decode_MKNOD3args - Decode a MKNOD3args argument
 * @rqstp: RPC transaction context
 * @xdr: source XDR data stream
 *
 * Return values:
 *   %true: procedure arguments decoded successfully
 *   %false: decode failed
 */
bool nfs_svc_decode_MKNOD3args(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct MKNOD3args *argp = rqstp->rq_argp;

	return xdrgen_decode_MKNOD3args(xdr, argp);
}

/**
 * nfs_svc_decode_REMOVE3args - Decode a REMOVE3args argument
 * @rqstp: RPC transaction context
 * @xdr: source XDR data stream
 *
 * Return values:
 *   %true: procedure arguments decoded successfully
 *   %false: decode failed
 */
bool nfs_svc_decode_REMOVE3args(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct REMOVE3args *argp = rqstp->rq_argp;

	return xdrgen_decode_REMOVE3args(xdr, argp);
}

/**
 * nfs_svc_decode_RMDIR3args - Decode a RMDIR3args argument
 * @rqstp: RPC transaction context
 * @xdr: source XDR data stream
 *
 * Return values:
 *   %true: procedure arguments decoded successfully
 *   %false: decode failed
 */
bool nfs_svc_decode_RMDIR3args(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct RMDIR3args *argp = rqstp->rq_argp;

	return xdrgen_decode_RMDIR3args(xdr, argp);
}

/**
 * nfs_svc_decode_RENAME3args - Decode a RENAME3args argument
 * @rqstp: RPC transaction context
 * @xdr: source XDR data stream
 *
 * Return values:
 *   %true: procedure arguments decoded successfully
 *   %false: decode failed
 */
bool nfs_svc_decode_RENAME3args(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct RENAME3args *argp = rqstp->rq_argp;

	return xdrgen_decode_RENAME3args(xdr, argp);
}

/**
 * nfs_svc_decode_LINK3args - Decode a LINK3args argument
 * @rqstp: RPC transaction context
 * @xdr: source XDR data stream
 *
 * Return values:
 *   %true: procedure arguments decoded successfully
 *   %false: decode failed
 */
bool nfs_svc_decode_LINK3args(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct LINK3args *argp = rqstp->rq_argp;

	return xdrgen_decode_LINK3args(xdr, argp);
}

/**
 * nfs_svc_decode_READDIR3args - Decode a READDIR3args argument
 * @rqstp: RPC transaction context
 * @xdr: source XDR data stream
 *
 * Return values:
 *   %true: procedure arguments decoded successfully
 *   %false: decode failed
 */
bool nfs_svc_decode_READDIR3args(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct READDIR3args *argp = rqstp->rq_argp;

	return xdrgen_decode_READDIR3args(xdr, argp);
}

/**
 * nfs_svc_decode_READDIRPLUS3args - Decode a READDIRPLUS3args argument
 * @rqstp: RPC transaction context
 * @xdr: source XDR data stream
 *
 * Return values:
 *   %true: procedure arguments decoded successfully
 *   %false: decode failed
 */
bool nfs_svc_decode_READDIRPLUS3args(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct READDIRPLUS3args *argp = rqstp->rq_argp;

	return xdrgen_decode_READDIRPLUS3args(xdr, argp);
}

/**
 * nfs_svc_decode_FSSTAT3args - Decode a FSSTAT3args argument
 * @rqstp: RPC transaction context
 * @xdr: source XDR data stream
 *
 * Return values:
 *   %true: procedure arguments decoded successfully
 *   %false: decode failed
 */
bool nfs_svc_decode_FSSTAT3args(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct FSSTAT3args *argp = rqstp->rq_argp;

	return xdrgen_decode_FSSTAT3args(xdr, argp);
}

/**
 * nfs_svc_decode_FSINFO3args - Decode a FSINFO3args argument
 * @rqstp: RPC transaction context
 * @xdr: source XDR data stream
 *
 * Return values:
 *   %true: procedure arguments decoded successfully
 *   %false: decode failed
 */
bool nfs_svc_decode_FSINFO3args(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct FSINFO3args *argp = rqstp->rq_argp;

	return xdrgen_decode_FSINFO3args(xdr, argp);
}

/**
 * nfs_svc_decode_PATHCONF3args - Decode a PATHCONF3args argument
 * @rqstp: RPC transaction context
 * @xdr: source XDR data stream
 *
 * Return values:
 *   %true: procedure arguments decoded successfully
 *   %false: decode failed
 */
bool nfs_svc_decode_PATHCONF3args(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct PATHCONF3args *argp = rqstp->rq_argp;

	return xdrgen_decode_PATHCONF3args(xdr, argp);
}

/**
 * nfs_svc_decode_COMMIT3args - Decode a COMMIT3args argument
 * @rqstp: RPC transaction context
 * @xdr: source XDR data stream
 *
 * Return values:
 *   %true: procedure arguments decoded successfully
 *   %false: decode failed
 */
bool nfs_svc_decode_COMMIT3args(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct COMMIT3args *argp = rqstp->rq_argp;

	return xdrgen_decode_COMMIT3args(xdr, argp);
}

static bool __maybe_unused
xdrgen_encode_uint64(struct xdr_stream *xdr, const uint64 value)
{
	return xdrgen_encode_unsigned_hyper(xdr, value);
}

static bool __maybe_unused
xdrgen_encode_int64(struct xdr_stream *xdr, const int64 value)
{
	return xdrgen_encode_hyper(xdr, value);
}

static bool __maybe_unused
xdrgen_encode_uint32(struct xdr_stream *xdr, const uint32 value)
{
	return xdrgen_encode_unsigned_long(xdr, value);
}

static bool __maybe_unused
xdrgen_encode_int32(struct xdr_stream *xdr, const int32 value)
{
	return xdrgen_encode_long(xdr, value);
}

static bool __maybe_unused
xdrgen_encode_filename3(struct xdr_stream *xdr, const filename3 value)
{
	return xdr_stream_encode_opaque(xdr, value.data, value.len) >= 0;
}

static bool __maybe_unused
xdrgen_encode_nfspath3(struct xdr_stream *xdr, const nfspath3 value)
{
	return xdr_stream_encode_opaque(xdr, value.data, value.len) >= 0;
}

static bool __maybe_unused
xdrgen_encode_fileid3(struct xdr_stream *xdr, const fileid3 value)
{
	return xdrgen_encode_uint64(xdr, value);
}

static bool __maybe_unused
xdrgen_encode_cookie3(struct xdr_stream *xdr, const cookie3 value)
{
	return xdrgen_encode_uint64(xdr, value);
}

static bool __maybe_unused
xdrgen_encode_cookieverf3(struct xdr_stream *xdr, const cookieverf3 value)
{
	return xdr_stream_encode_opaque_fixed(xdr, value, NFS3_COOKIEVERFSIZE) >= 0;
}

static bool __maybe_unused
xdrgen_encode_createverf3(struct xdr_stream *xdr, const createverf3 value)
{
	return xdr_stream_encode_opaque_fixed(xdr, value, NFS3_CREATEVERFSIZE) >= 0;
}

static bool __maybe_unused
xdrgen_encode_writeverf3(struct xdr_stream *xdr, const writeverf3 value)
{
	return xdr_stream_encode_opaque_fixed(xdr, value, NFS3_WRITEVERFSIZE) >= 0;
}

static bool __maybe_unused
xdrgen_encode_uid3(struct xdr_stream *xdr, const uid3 value)
{
	return xdrgen_encode_uint32(xdr, value);
}

static bool __maybe_unused
xdrgen_encode_gid3(struct xdr_stream *xdr, const gid3 value)
{
	return xdrgen_encode_uint32(xdr, value);
}

static bool __maybe_unused
xdrgen_encode_size3(struct xdr_stream *xdr, const size3 value)
{
	return xdrgen_encode_uint64(xdr, value);
}

static bool __maybe_unused
xdrgen_encode_offset3(struct xdr_stream *xdr, const offset3 value)
{
	return xdrgen_encode_uint64(xdr, value);
}

static bool __maybe_unused
xdrgen_encode_mode3(struct xdr_stream *xdr, const mode3 value)
{
	return xdrgen_encode_uint32(xdr, value);
}

static bool __maybe_unused
xdrgen_encode_count3(struct xdr_stream *xdr, const count3 value)
{
	return xdrgen_encode_uint32(xdr, value);
}

static bool __maybe_unused
xdrgen_encode_nfsstat3(struct xdr_stream *xdr, nfsstat3 value)
{
	return xdr_stream_encode_be32(xdr, value) == XDR_UNIT;
}

static bool __maybe_unused
xdrgen_encode_ftype3(struct xdr_stream *xdr, ftype3 value)
{
	return xdr_stream_encode_u32(xdr, value) == XDR_UNIT;
}

static bool __maybe_unused
xdrgen_encode_specdata3(struct xdr_stream *xdr, const struct specdata3 *value)
{
	if (!xdrgen_encode_uint32(xdr, value->specdata1))
		return false;
	if (!xdrgen_encode_uint32(xdr, value->specdata2))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_nfs_fh3(struct xdr_stream *xdr, const struct nfs_fh3 *value)
{
	if (value->data.len > NFS3_FHSIZE)
		return false;
	if (xdr_stream_encode_opaque(xdr, value->data.data, value->data.len) < 0)
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_nfstime3(struct xdr_stream *xdr, const struct nfstime3 *value)
{
	if (!xdrgen_encode_uint32(xdr, value->seconds))
		return false;
	if (!xdrgen_encode_uint32(xdr, value->nseconds))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_fattr3(struct xdr_stream *xdr, const struct fattr3 *value)
{
	if (!xdrgen_encode_ftype3(xdr, value->type))
		return false;
	if (!xdrgen_encode_mode3(xdr, value->mode))
		return false;
	if (!xdrgen_encode_uint32(xdr, value->nlink))
		return false;
	if (!xdrgen_encode_uid3(xdr, value->uid))
		return false;
	if (!xdrgen_encode_gid3(xdr, value->gid))
		return false;
	if (!xdrgen_encode_size3(xdr, value->size))
		return false;
	if (!xdrgen_encode_size3(xdr, value->used))
		return false;
	if (!xdrgen_encode_specdata3(xdr, &value->rdev))
		return false;
	if (!xdrgen_encode_uint64(xdr, value->fsid))
		return false;
	if (!xdrgen_encode_fileid3(xdr, value->fileid))
		return false;
	if (!xdrgen_encode_nfstime3(xdr, &value->atime))
		return false;
	if (!xdrgen_encode_nfstime3(xdr, &value->mtime))
		return false;
	if (!xdrgen_encode_nfstime3(xdr, &value->ctime))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_post_op_attr(struct xdr_stream *xdr, const struct post_op_attr *ptr)
{
	if (!xdrgen_encode_bool(xdr, ptr->attributes_follow))
		return false;
	if (ptr->attributes_follow) {
		if (!xdrgen_encode_fattr3(xdr, &ptr->u.attributes))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_wcc_attr(struct xdr_stream *xdr, const struct wcc_attr *value)
{
	if (!xdrgen_encode_size3(xdr, value->size))
		return false;
	if (!xdrgen_encode_nfstime3(xdr, &value->mtime))
		return false;
	if (!xdrgen_encode_nfstime3(xdr, &value->ctime))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_pre_op_attr(struct xdr_stream *xdr, const struct pre_op_attr *ptr)
{
	if (!xdrgen_encode_bool(xdr, ptr->attributes_follow))
		return false;
	if (ptr->attributes_follow) {
		if (!xdrgen_encode_wcc_attr(xdr, &ptr->u.attributes))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_wcc_data(struct xdr_stream *xdr, const struct wcc_data *value)
{
	if (!xdrgen_encode_pre_op_attr(xdr, &value->before))
		return false;
	if (!xdrgen_encode_post_op_attr(xdr, &value->after))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_post_op_fh3(struct xdr_stream *xdr, const struct post_op_fh3 *ptr)
{
	if (!xdrgen_encode_bool(xdr, ptr->handle_follows))
		return false;
	if (ptr->handle_follows) {
		if (!xdrgen_encode_nfs_fh3(xdr, &ptr->u.handle))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_time_how(struct xdr_stream *xdr, time_how value)
{
	return xdr_stream_encode_u32(xdr, value) == XDR_UNIT;
}

static bool __maybe_unused
xdrgen_encode_set_mode3(struct xdr_stream *xdr, const struct set_mode3 *ptr)
{
	if (!xdrgen_encode_bool(xdr, ptr->set_it))
		return false;
	if (ptr->set_it) {
		if (!xdrgen_encode_mode3(xdr, ptr->u.mode))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_set_uid3(struct xdr_stream *xdr, const struct set_uid3 *ptr)
{
	if (!xdrgen_encode_bool(xdr, ptr->set_it))
		return false;
	if (ptr->set_it) {
		if (!xdrgen_encode_uid3(xdr, ptr->u.uid))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_set_gid3(struct xdr_stream *xdr, const struct set_gid3 *ptr)
{
	if (!xdrgen_encode_bool(xdr, ptr->set_it))
		return false;
	if (ptr->set_it) {
		if (!xdrgen_encode_gid3(xdr, ptr->u.gid))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_set_size3(struct xdr_stream *xdr, const struct set_size3 *ptr)
{
	if (!xdrgen_encode_bool(xdr, ptr->set_it))
		return false;
	if (ptr->set_it) {
		if (!xdrgen_encode_size3(xdr, ptr->u.size))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_set_atime(struct xdr_stream *xdr, const struct set_atime *ptr)
{
	if (!xdrgen_encode_time_how(xdr, ptr->set_it))
		return false;
	switch (ptr->set_it) {
	case SET_TO_CLIENT_TIME:
		if (!xdrgen_encode_nfstime3(xdr, &ptr->u.atime))
			return false;
		break;
	default:
		break;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_set_mtime(struct xdr_stream *xdr, const struct set_mtime *ptr)
{
	if (!xdrgen_encode_time_how(xdr, ptr->set_it))
		return false;
	switch (ptr->set_it) {
	case SET_TO_CLIENT_TIME:
		if (!xdrgen_encode_nfstime3(xdr, &ptr->u.mtime))
			return false;
		break;
	default:
		break;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_sattr3(struct xdr_stream *xdr, const struct sattr3 *value)
{
	if (!xdrgen_encode_set_mode3(xdr, &value->mode))
		return false;
	if (!xdrgen_encode_set_uid3(xdr, &value->uid))
		return false;
	if (!xdrgen_encode_set_gid3(xdr, &value->gid))
		return false;
	if (!xdrgen_encode_set_size3(xdr, &value->size))
		return false;
	if (!xdrgen_encode_set_atime(xdr, &value->atime))
		return false;
	if (!xdrgen_encode_set_mtime(xdr, &value->mtime))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_diropargs3(struct xdr_stream *xdr, const struct diropargs3 *value)
{
	if (!xdrgen_encode_nfs_fh3(xdr, &value->dir))
		return false;
	if (!xdrgen_encode_filename3(xdr, value->name))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_GETATTR3args(struct xdr_stream *xdr, const struct GETATTR3args *value)
{
	if (!xdrgen_encode_nfs_fh3(xdr, &value->object))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_GETATTR3resok(struct xdr_stream *xdr, const struct GETATTR3resok *value)
{
	if (!xdrgen_encode_fattr3(xdr, &value->obj_attributes))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_GETATTR3res(struct xdr_stream *xdr, const struct GETATTR3res *ptr)
{
	if (!xdrgen_encode_nfsstat3(xdr, ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_encode_GETATTR3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		break;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_sattrguard3(struct xdr_stream *xdr, const struct sattrguard3 *ptr)
{
	if (!xdrgen_encode_bool(xdr, ptr->check))
		return false;
	if (ptr->check) {
		if (!xdrgen_encode_nfstime3(xdr, &ptr->u.obj_ctime))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_SETATTR3args(struct xdr_stream *xdr, const struct SETATTR3args *value)
{
	if (!xdrgen_encode_nfs_fh3(xdr, &value->object))
		return false;
	if (!xdrgen_encode_sattr3(xdr, &value->new_attributes))
		return false;
	if (!xdrgen_encode_sattrguard3(xdr, &value->guard))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_SETATTR3resok(struct xdr_stream *xdr, const struct SETATTR3resok *value)
{
	if (!xdrgen_encode_wcc_data(xdr, &value->obj_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_SETATTR3resfail(struct xdr_stream *xdr, const struct SETATTR3resfail *value)
{
	if (!xdrgen_encode_wcc_data(xdr, &value->obj_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_SETATTR3res(struct xdr_stream *xdr, const struct SETATTR3res *ptr)
{
	if (!xdrgen_encode_nfsstat3(xdr, ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_encode_SETATTR3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_encode_SETATTR3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_LOOKUP3args(struct xdr_stream *xdr, const struct LOOKUP3args *value)
{
	if (!xdrgen_encode_diropargs3(xdr, &value->what))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_LOOKUP3resok(struct xdr_stream *xdr, const struct LOOKUP3resok *value)
{
	if (!xdrgen_encode_nfs_fh3(xdr, &value->object))
		return false;
	if (!xdrgen_encode_post_op_attr(xdr, &value->obj_attributes))
		return false;
	if (!xdrgen_encode_post_op_attr(xdr, &value->dir_attributes))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_LOOKUP3resfail(struct xdr_stream *xdr, const struct LOOKUP3resfail *value)
{
	if (!xdrgen_encode_post_op_attr(xdr, &value->dir_attributes))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_LOOKUP3res(struct xdr_stream *xdr, const struct LOOKUP3res *ptr)
{
	if (!xdrgen_encode_nfsstat3(xdr, ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_encode_LOOKUP3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_encode_LOOKUP3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_ACCESS3args(struct xdr_stream *xdr, const struct ACCESS3args *value)
{
	if (!xdrgen_encode_nfs_fh3(xdr, &value->object))
		return false;
	if (!xdrgen_encode_uint32(xdr, value->access))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_ACCESS3resok(struct xdr_stream *xdr, const struct ACCESS3resok *value)
{
	if (!xdrgen_encode_post_op_attr(xdr, &value->obj_attributes))
		return false;
	if (!xdrgen_encode_uint32(xdr, value->access))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_ACCESS3resfail(struct xdr_stream *xdr, const struct ACCESS3resfail *value)
{
	if (!xdrgen_encode_post_op_attr(xdr, &value->obj_attributes))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_ACCESS3res(struct xdr_stream *xdr, const struct ACCESS3res *ptr)
{
	if (!xdrgen_encode_nfsstat3(xdr, ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_encode_ACCESS3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_encode_ACCESS3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_READLINK3args(struct xdr_stream *xdr, const struct READLINK3args *value)
{
	if (!xdrgen_encode_nfs_fh3(xdr, &value->symlink))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_READLINK3resok(struct xdr_stream *xdr, const struct READLINK3resok *value)
{
	if (!xdrgen_encode_post_op_attr(xdr, &value->symlink_attributes))
		return false;
	if (!xdrgen_encode_nfspath3(xdr, value->data))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_READLINK3resfail(struct xdr_stream *xdr, const struct READLINK3resfail *value)
{
	if (!xdrgen_encode_post_op_attr(xdr, &value->symlink_attributes))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_READLINK3res(struct xdr_stream *xdr, const struct READLINK3res *ptr)
{
	if (!xdrgen_encode_nfsstat3(xdr, ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_encode_READLINK3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_encode_READLINK3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_READ3args(struct xdr_stream *xdr, const struct READ3args *value)
{
	if (!xdrgen_encode_nfs_fh3(xdr, &value->file))
		return false;
	if (!xdrgen_encode_offset3(xdr, value->offset))
		return false;
	if (!xdrgen_encode_count3(xdr, value->count))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_READ3resok(struct xdr_stream *xdr, const struct READ3resok *value)
{
	if (!xdrgen_encode_post_op_attr(xdr, &value->file_attributes))
		return false;
	if (!xdrgen_encode_count3(xdr, value->count))
		return false;
	if (!xdrgen_encode_bool(xdr, value->eof))
		return false;
	if (value->data.len > 0)
		return false;
	if (xdr_stream_encode_opaque(xdr, value->data.data, value->data.len) < 0)
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_READ3resfail(struct xdr_stream *xdr, const struct READ3resfail *value)
{
	if (!xdrgen_encode_post_op_attr(xdr, &value->file_attributes))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_READ3res(struct xdr_stream *xdr, const struct READ3res *ptr)
{
	if (!xdrgen_encode_nfsstat3(xdr, ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_encode_READ3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_encode_READ3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_stable_how(struct xdr_stream *xdr, stable_how value)
{
	return xdr_stream_encode_u32(xdr, value) == XDR_UNIT;
}

static bool __maybe_unused
xdrgen_encode_WRITE3args(struct xdr_stream *xdr, const struct WRITE3args *value)
{
	if (!xdrgen_encode_nfs_fh3(xdr, &value->file))
		return false;
	if (!xdrgen_encode_offset3(xdr, value->offset))
		return false;
	if (!xdrgen_encode_count3(xdr, value->count))
		return false;
	if (!xdrgen_encode_stable_how(xdr, value->stable))
		return false;
	if (value->data.len > 0)
		return false;
	if (xdr_stream_encode_opaque(xdr, value->data.data, value->data.len) < 0)
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_WRITE3resok(struct xdr_stream *xdr, const struct WRITE3resok *value)
{
	if (!xdrgen_encode_wcc_data(xdr, &value->file_wcc))
		return false;
	if (!xdrgen_encode_count3(xdr, value->count))
		return false;
	if (!xdrgen_encode_stable_how(xdr, value->committed))
		return false;
	if (!xdrgen_encode_writeverf3(xdr, value->verf))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_WRITE3resfail(struct xdr_stream *xdr, const struct WRITE3resfail *value)
{
	if (!xdrgen_encode_wcc_data(xdr, &value->file_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_WRITE3res(struct xdr_stream *xdr, const struct WRITE3res *ptr)
{
	if (!xdrgen_encode_nfsstat3(xdr, ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_encode_WRITE3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_encode_WRITE3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_createmode3(struct xdr_stream *xdr, createmode3 value)
{
	return xdr_stream_encode_u32(xdr, value) == XDR_UNIT;
}

static bool __maybe_unused
xdrgen_encode_createhow3(struct xdr_stream *xdr, const struct createhow3 *ptr)
{
	if (!xdrgen_encode_createmode3(xdr, ptr->mode))
		return false;
	switch (ptr->mode) {
	case UNCHECKED:
	case GUARDED:
		if (!xdrgen_encode_sattr3(xdr, &ptr->u.obj_attributes))
			return false;
		break;
	case EXCLUSIVE:
		if (!xdrgen_encode_createverf3(xdr, ptr->u.verf))
			return false;
		break;
	default:
		break;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_CREATE3args(struct xdr_stream *xdr, const struct CREATE3args *value)
{
	if (!xdrgen_encode_diropargs3(xdr, &value->where))
		return false;
	if (!xdrgen_encode_createhow3(xdr, &value->how))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_CREATE3resok(struct xdr_stream *xdr, const struct CREATE3resok *value)
{
	if (!xdrgen_encode_post_op_fh3(xdr, &value->obj))
		return false;
	if (!xdrgen_encode_post_op_attr(xdr, &value->obj_attributes))
		return false;
	if (!xdrgen_encode_wcc_data(xdr, &value->dir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_CREATE3resfail(struct xdr_stream *xdr, const struct CREATE3resfail *value)
{
	if (!xdrgen_encode_wcc_data(xdr, &value->dir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_CREATE3res(struct xdr_stream *xdr, const struct CREATE3res *ptr)
{
	if (!xdrgen_encode_nfsstat3(xdr, ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_encode_CREATE3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_encode_CREATE3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_MKDIR3args(struct xdr_stream *xdr, const struct MKDIR3args *value)
{
	if (!xdrgen_encode_diropargs3(xdr, &value->where))
		return false;
	if (!xdrgen_encode_sattr3(xdr, &value->attributes))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_MKDIR3resok(struct xdr_stream *xdr, const struct MKDIR3resok *value)
{
	if (!xdrgen_encode_post_op_fh3(xdr, &value->obj))
		return false;
	if (!xdrgen_encode_post_op_attr(xdr, &value->obj_attributes))
		return false;
	if (!xdrgen_encode_wcc_data(xdr, &value->dir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_MKDIR3resfail(struct xdr_stream *xdr, const struct MKDIR3resfail *value)
{
	if (!xdrgen_encode_wcc_data(xdr, &value->dir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_MKDIR3res(struct xdr_stream *xdr, const struct MKDIR3res *ptr)
{
	if (!xdrgen_encode_nfsstat3(xdr, ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_encode_MKDIR3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_encode_MKDIR3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_symlinkdata3(struct xdr_stream *xdr, const struct symlinkdata3 *value)
{
	if (!xdrgen_encode_sattr3(xdr, &value->symlink_attributes))
		return false;
	if (!xdrgen_encode_nfspath3(xdr, value->symlink_data))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_SYMLINK3args(struct xdr_stream *xdr, const struct SYMLINK3args *value)
{
	if (!xdrgen_encode_diropargs3(xdr, &value->where))
		return false;
	if (!xdrgen_encode_symlinkdata3(xdr, &value->symlink))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_SYMLINK3resok(struct xdr_stream *xdr, const struct SYMLINK3resok *value)
{
	if (!xdrgen_encode_post_op_fh3(xdr, &value->obj))
		return false;
	if (!xdrgen_encode_post_op_attr(xdr, &value->obj_attributes))
		return false;
	if (!xdrgen_encode_wcc_data(xdr, &value->dir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_SYMLINK3resfail(struct xdr_stream *xdr, const struct SYMLINK3resfail *value)
{
	if (!xdrgen_encode_wcc_data(xdr, &value->dir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_SYMLINK3res(struct xdr_stream *xdr, const struct SYMLINK3res *ptr)
{
	if (!xdrgen_encode_nfsstat3(xdr, ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_encode_SYMLINK3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_encode_SYMLINK3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_devicedata3(struct xdr_stream *xdr, const struct devicedata3 *value)
{
	if (!xdrgen_encode_sattr3(xdr, &value->dev_attributes))
		return false;
	if (!xdrgen_encode_specdata3(xdr, &value->spec))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_mknoddata3(struct xdr_stream *xdr, const struct mknoddata3 *ptr)
{
	if (!xdrgen_encode_ftype3(xdr, ptr->type))
		return false;
	switch (ptr->type) {
	case NF3CHR:
	case NF3BLK:
		if (!xdrgen_encode_devicedata3(xdr, &ptr->u.device))
			return false;
		break;
	case NF3SOCK:
	case NF3FIFO:
		if (!xdrgen_encode_sattr3(xdr, &ptr->u.pipe_attributes))
			return false;
		break;
	default:
		break;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_MKNOD3args(struct xdr_stream *xdr, const struct MKNOD3args *value)
{
	if (!xdrgen_encode_diropargs3(xdr, &value->where))
		return false;
	if (!xdrgen_encode_mknoddata3(xdr, &value->what))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_MKNOD3resok(struct xdr_stream *xdr, const struct MKNOD3resok *value)
{
	if (!xdrgen_encode_post_op_fh3(xdr, &value->obj))
		return false;
	if (!xdrgen_encode_post_op_attr(xdr, &value->obj_attributes))
		return false;
	if (!xdrgen_encode_wcc_data(xdr, &value->dir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_MKNOD3resfail(struct xdr_stream *xdr, const struct MKNOD3resfail *value)
{
	if (!xdrgen_encode_wcc_data(xdr, &value->dir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_MKNOD3res(struct xdr_stream *xdr, const struct MKNOD3res *ptr)
{
	if (!xdrgen_encode_nfsstat3(xdr, ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_encode_MKNOD3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_encode_MKNOD3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_REMOVE3args(struct xdr_stream *xdr, const struct REMOVE3args *value)
{
	if (!xdrgen_encode_diropargs3(xdr, &value->object))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_REMOVE3resok(struct xdr_stream *xdr, const struct REMOVE3resok *value)
{
	if (!xdrgen_encode_wcc_data(xdr, &value->dir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_REMOVE3resfail(struct xdr_stream *xdr, const struct REMOVE3resfail *value)
{
	if (!xdrgen_encode_wcc_data(xdr, &value->dir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_REMOVE3res(struct xdr_stream *xdr, const struct REMOVE3res *ptr)
{
	if (!xdrgen_encode_nfsstat3(xdr, ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_encode_REMOVE3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_encode_REMOVE3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_RMDIR3args(struct xdr_stream *xdr, const struct RMDIR3args *value)
{
	if (!xdrgen_encode_diropargs3(xdr, &value->object))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_RMDIR3resok(struct xdr_stream *xdr, const struct RMDIR3resok *value)
{
	if (!xdrgen_encode_wcc_data(xdr, &value->dir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_RMDIR3resfail(struct xdr_stream *xdr, const struct RMDIR3resfail *value)
{
	if (!xdrgen_encode_wcc_data(xdr, &value->dir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_RMDIR3res(struct xdr_stream *xdr, const struct RMDIR3res *ptr)
{
	if (!xdrgen_encode_nfsstat3(xdr, ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_encode_RMDIR3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_encode_RMDIR3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_RENAME3args(struct xdr_stream *xdr, const struct RENAME3args *value)
{
	if (!xdrgen_encode_diropargs3(xdr, &value->from))
		return false;
	if (!xdrgen_encode_diropargs3(xdr, &value->to))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_RENAME3resok(struct xdr_stream *xdr, const struct RENAME3resok *value)
{
	if (!xdrgen_encode_wcc_data(xdr, &value->fromdir_wcc))
		return false;
	if (!xdrgen_encode_wcc_data(xdr, &value->todir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_RENAME3resfail(struct xdr_stream *xdr, const struct RENAME3resfail *value)
{
	if (!xdrgen_encode_wcc_data(xdr, &value->fromdir_wcc))
		return false;
	if (!xdrgen_encode_wcc_data(xdr, &value->todir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_RENAME3res(struct xdr_stream *xdr, const struct RENAME3res *ptr)
{
	if (!xdrgen_encode_nfsstat3(xdr, ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_encode_RENAME3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_encode_RENAME3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_LINK3args(struct xdr_stream *xdr, const struct LINK3args *value)
{
	if (!xdrgen_encode_nfs_fh3(xdr, &value->file))
		return false;
	if (!xdrgen_encode_diropargs3(xdr, &value->link))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_LINK3resok(struct xdr_stream *xdr, const struct LINK3resok *value)
{
	if (!xdrgen_encode_post_op_attr(xdr, &value->file_attributes))
		return false;
	if (!xdrgen_encode_wcc_data(xdr, &value->linkdir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_LINK3resfail(struct xdr_stream *xdr, const struct LINK3resfail *value)
{
	if (!xdrgen_encode_post_op_attr(xdr, &value->file_attributes))
		return false;
	if (!xdrgen_encode_wcc_data(xdr, &value->linkdir_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_LINK3res(struct xdr_stream *xdr, const struct LINK3res *ptr)
{
	if (!xdrgen_encode_nfsstat3(xdr, ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_encode_LINK3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_encode_LINK3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_READDIR3args(struct xdr_stream *xdr, const struct READDIR3args *value)
{
	if (!xdrgen_encode_nfs_fh3(xdr, &value->dir))
		return false;
	if (!xdrgen_encode_cookie3(xdr, value->cookie))
		return false;
	if (!xdrgen_encode_cookieverf3(xdr, value->cookieverf))
		return false;
	if (!xdrgen_encode_count3(xdr, value->count))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_entry3(struct xdr_stream *xdr, const struct entry3 *value)
{
	if (!xdrgen_encode_bool(xdr, value != NULL))
		return false;
	if (!value)
		return true;

	if (!xdrgen_encode_fileid3(xdr, value->fileid))
		return false;
	if (!xdrgen_encode_filename3(xdr, value->name))
		return false;
	if (!xdrgen_encode_cookie3(xdr, value->cookie))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_dirlist3(struct xdr_stream *xdr, const struct dirlist3 *value)
{
	if (!xdrgen_encode_entry3(xdr, value->entries))
		return false;
	if (!xdrgen_encode_bool(xdr, value->eof))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_READDIR3resok(struct xdr_stream *xdr, const struct READDIR3resok *value)
{
	if (!xdrgen_encode_post_op_attr(xdr, &value->dir_attributes))
		return false;
	if (!xdrgen_encode_cookieverf3(xdr, value->cookieverf))
		return false;
	if (!xdrgen_encode_dirlist3(xdr, &value->reply))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_READDIR3resfail(struct xdr_stream *xdr, const struct READDIR3resfail *value)
{
	if (!xdrgen_encode_post_op_attr(xdr, &value->dir_attributes))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_READDIR3res(struct xdr_stream *xdr, const struct READDIR3res *ptr)
{
	if (!xdrgen_encode_nfsstat3(xdr, ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_encode_READDIR3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_encode_READDIR3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_READDIRPLUS3args(struct xdr_stream *xdr, const struct READDIRPLUS3args *value)
{
	if (!xdrgen_encode_nfs_fh3(xdr, &value->dir))
		return false;
	if (!xdrgen_encode_cookie3(xdr, value->cookie))
		return false;
	if (!xdrgen_encode_cookieverf3(xdr, value->cookieverf))
		return false;
	if (!xdrgen_encode_count3(xdr, value->dircount))
		return false;
	if (!xdrgen_encode_count3(xdr, value->maxcount))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_entryplus3(struct xdr_stream *xdr, const struct entryplus3 *value)
{
	if (!xdrgen_encode_bool(xdr, value != NULL))
		return false;
	if (!value)
		return true;

	if (!xdrgen_encode_fileid3(xdr, value->fileid))
		return false;
	if (!xdrgen_encode_filename3(xdr, value->name))
		return false;
	if (!xdrgen_encode_cookie3(xdr, value->cookie))
		return false;
	if (!xdrgen_encode_post_op_attr(xdr, &value->name_attributes))
		return false;
	if (!xdrgen_encode_post_op_fh3(xdr, &value->name_handle))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_dirlistplus3(struct xdr_stream *xdr, const struct dirlistplus3 *value)
{
	if (!xdrgen_encode_entryplus3(xdr, value->entries))
		return false;
	if (!xdrgen_encode_bool(xdr, value->eof))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_READDIRPLUS3resok(struct xdr_stream *xdr, const struct READDIRPLUS3resok *value)
{
	if (!xdrgen_encode_post_op_attr(xdr, &value->dir_attributes))
		return false;
	if (!xdrgen_encode_cookieverf3(xdr, value->cookieverf))
		return false;
	if (!xdrgen_encode_dirlistplus3(xdr, &value->reply))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_READDIRPLUS3resfail(struct xdr_stream *xdr, const struct READDIRPLUS3resfail *value)
{
	if (!xdrgen_encode_post_op_attr(xdr, &value->dir_attributes))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_READDIRPLUS3res(struct xdr_stream *xdr, const struct READDIRPLUS3res *ptr)
{
	if (!xdrgen_encode_nfsstat3(xdr, ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_encode_READDIRPLUS3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_encode_READDIRPLUS3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_FSSTAT3args(struct xdr_stream *xdr, const struct FSSTAT3args *value)
{
	if (!xdrgen_encode_nfs_fh3(xdr, &value->fsroot))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_FSSTAT3resok(struct xdr_stream *xdr, const struct FSSTAT3resok *value)
{
	if (!xdrgen_encode_post_op_attr(xdr, &value->obj_attributes))
		return false;
	if (!xdrgen_encode_size3(xdr, value->tbytes))
		return false;
	if (!xdrgen_encode_size3(xdr, value->fbytes))
		return false;
	if (!xdrgen_encode_size3(xdr, value->abytes))
		return false;
	if (!xdrgen_encode_size3(xdr, value->tfiles))
		return false;
	if (!xdrgen_encode_size3(xdr, value->ffiles))
		return false;
	if (!xdrgen_encode_size3(xdr, value->afiles))
		return false;
	if (!xdrgen_encode_uint32(xdr, value->invarsec))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_FSSTAT3resfail(struct xdr_stream *xdr, const struct FSSTAT3resfail *value)
{
	if (!xdrgen_encode_post_op_attr(xdr, &value->obj_attributes))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_FSSTAT3res(struct xdr_stream *xdr, const struct FSSTAT3res *ptr)
{
	if (!xdrgen_encode_nfsstat3(xdr, ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_encode_FSSTAT3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_encode_FSSTAT3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_FSINFO3args(struct xdr_stream *xdr, const struct FSINFO3args *value)
{
	if (!xdrgen_encode_nfs_fh3(xdr, &value->fsroot))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_FSINFO3resok(struct xdr_stream *xdr, const struct FSINFO3resok *value)
{
	if (!xdrgen_encode_post_op_attr(xdr, &value->obj_attributes))
		return false;
	if (!xdrgen_encode_uint32(xdr, value->rtmax))
		return false;
	if (!xdrgen_encode_uint32(xdr, value->rtpref))
		return false;
	if (!xdrgen_encode_uint32(xdr, value->rtmult))
		return false;
	if (!xdrgen_encode_uint32(xdr, value->wtmax))
		return false;
	if (!xdrgen_encode_uint32(xdr, value->wtpref))
		return false;
	if (!xdrgen_encode_uint32(xdr, value->wtmult))
		return false;
	if (!xdrgen_encode_uint32(xdr, value->dtpref))
		return false;
	if (!xdrgen_encode_size3(xdr, value->maxfilesize))
		return false;
	if (!xdrgen_encode_nfstime3(xdr, &value->time_delta))
		return false;
	if (!xdrgen_encode_uint32(xdr, value->properties))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_FSINFO3resfail(struct xdr_stream *xdr, const struct FSINFO3resfail *value)
{
	if (!xdrgen_encode_post_op_attr(xdr, &value->obj_attributes))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_FSINFO3res(struct xdr_stream *xdr, const struct FSINFO3res *ptr)
{
	if (!xdrgen_encode_nfsstat3(xdr, ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_encode_FSINFO3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_encode_FSINFO3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_PATHCONF3args(struct xdr_stream *xdr, const struct PATHCONF3args *value)
{
	if (!xdrgen_encode_nfs_fh3(xdr, &value->object))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_PATHCONF3resok(struct xdr_stream *xdr, const struct PATHCONF3resok *value)
{
	if (!xdrgen_encode_post_op_attr(xdr, &value->obj_attributes))
		return false;
	if (!xdrgen_encode_uint32(xdr, value->linkmax))
		return false;
	if (!xdrgen_encode_uint32(xdr, value->name_max))
		return false;
	if (!xdrgen_encode_bool(xdr, value->no_trunc))
		return false;
	if (!xdrgen_encode_bool(xdr, value->chown_restricted))
		return false;
	if (!xdrgen_encode_bool(xdr, value->case_insensitive))
		return false;
	if (!xdrgen_encode_bool(xdr, value->case_preserving))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_PATHCONF3resfail(struct xdr_stream *xdr, const struct PATHCONF3resfail *value)
{
	if (!xdrgen_encode_post_op_attr(xdr, &value->obj_attributes))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_PATHCONF3res(struct xdr_stream *xdr, const struct PATHCONF3res *ptr)
{
	if (!xdrgen_encode_nfsstat3(xdr, ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_encode_PATHCONF3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_encode_PATHCONF3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

static bool __maybe_unused
xdrgen_encode_COMMIT3args(struct xdr_stream *xdr, const struct COMMIT3args *value)
{
	if (!xdrgen_encode_nfs_fh3(xdr, &value->file))
		return false;
	if (!xdrgen_encode_offset3(xdr, value->offset))
		return false;
	if (!xdrgen_encode_count3(xdr, value->count))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_COMMIT3resok(struct xdr_stream *xdr, const struct COMMIT3resok *value)
{
	if (!xdrgen_encode_wcc_data(xdr, &value->file_wcc))
		return false;
	if (!xdrgen_encode_writeverf3(xdr, value->verf))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_COMMIT3resfail(struct xdr_stream *xdr, const struct COMMIT3resfail *value)
{
	if (!xdrgen_encode_wcc_data(xdr, &value->file_wcc))
		return false;
	return true;
}

static bool __maybe_unused
xdrgen_encode_COMMIT3res(struct xdr_stream *xdr, const struct COMMIT3res *ptr)
{
	if (!xdrgen_encode_nfsstat3(xdr, ptr->status))
		return false;
	switch (ptr->status) {
	case __constant_cpu_to_be32(NFS3_OK):
		if (!xdrgen_encode_COMMIT3resok(xdr, &ptr->u.resok))
			return false;
		break;
	default:
		if (!xdrgen_encode_COMMIT3resfail(xdr, &ptr->u.resfail))
			return false;
	}
	return true;
}

/**
 * nfs_svc_encode_void - Encode a void result
 * @rqstp: RPC transaction context
 * @xdr: target XDR data stream
 *
 * Return values:
 *   %true: procedure results encoded successfully
 *   %false: encode failed
 */
bool nfs_svc_encode_void(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	return xdrgen_encode_void(xdr);
}

/**
 * nfs_svc_encode_GETATTR3res - Encode a GETATTR3res result
 * @rqstp: RPC transaction context
 * @xdr: target XDR data stream
 *
 * Return values:
 *   %true: procedure results encoded successfully
 *   %false: encode failed
 */
bool nfs_svc_encode_GETATTR3res(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct GETATTR3res *resp = rqstp->rq_resp;

	return xdrgen_encode_GETATTR3res(xdr, resp);
}

/**
 * nfs_svc_encode_SETATTR3res - Encode a SETATTR3res result
 * @rqstp: RPC transaction context
 * @xdr: target XDR data stream
 *
 * Return values:
 *   %true: procedure results encoded successfully
 *   %false: encode failed
 */
bool nfs_svc_encode_SETATTR3res(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct SETATTR3res *resp = rqstp->rq_resp;

	return xdrgen_encode_SETATTR3res(xdr, resp);
}

/**
 * nfs_svc_encode_LOOKUP3res - Encode a LOOKUP3res result
 * @rqstp: RPC transaction context
 * @xdr: target XDR data stream
 *
 * Return values:
 *   %true: procedure results encoded successfully
 *   %false: encode failed
 */
bool nfs_svc_encode_LOOKUP3res(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct LOOKUP3res *resp = rqstp->rq_resp;

	return xdrgen_encode_LOOKUP3res(xdr, resp);
}

/**
 * nfs_svc_encode_ACCESS3res - Encode a ACCESS3res result
 * @rqstp: RPC transaction context
 * @xdr: target XDR data stream
 *
 * Return values:
 *   %true: procedure results encoded successfully
 *   %false: encode failed
 */
bool nfs_svc_encode_ACCESS3res(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct ACCESS3res *resp = rqstp->rq_resp;

	return xdrgen_encode_ACCESS3res(xdr, resp);
}

/**
 * nfs_svc_encode_READLINK3res - Encode a READLINK3res result
 * @rqstp: RPC transaction context
 * @xdr: target XDR data stream
 *
 * Return values:
 *   %true: procedure results encoded successfully
 *   %false: encode failed
 */
bool nfs_svc_encode_READLINK3res(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct READLINK3res *resp = rqstp->rq_resp;

	return xdrgen_encode_READLINK3res(xdr, resp);
}

/**
 * nfs_svc_encode_READ3res - Encode a READ3res result
 * @rqstp: RPC transaction context
 * @xdr: target XDR data stream
 *
 * Return values:
 *   %true: procedure results encoded successfully
 *   %false: encode failed
 */
bool nfs_svc_encode_READ3res(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct READ3res *resp = rqstp->rq_resp;

	return xdrgen_encode_READ3res(xdr, resp);
}

/**
 * nfs_svc_encode_WRITE3res - Encode a WRITE3res result
 * @rqstp: RPC transaction context
 * @xdr: target XDR data stream
 *
 * Return values:
 *   %true: procedure results encoded successfully
 *   %false: encode failed
 */
bool nfs_svc_encode_WRITE3res(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct WRITE3res *resp = rqstp->rq_resp;

	return xdrgen_encode_WRITE3res(xdr, resp);
}

/**
 * nfs_svc_encode_CREATE3res - Encode a CREATE3res result
 * @rqstp: RPC transaction context
 * @xdr: target XDR data stream
 *
 * Return values:
 *   %true: procedure results encoded successfully
 *   %false: encode failed
 */
bool nfs_svc_encode_CREATE3res(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct CREATE3res *resp = rqstp->rq_resp;

	return xdrgen_encode_CREATE3res(xdr, resp);
}

/**
 * nfs_svc_encode_MKDIR3res - Encode a MKDIR3res result
 * @rqstp: RPC transaction context
 * @xdr: target XDR data stream
 *
 * Return values:
 *   %true: procedure results encoded successfully
 *   %false: encode failed
 */
bool nfs_svc_encode_MKDIR3res(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct MKDIR3res *resp = rqstp->rq_resp;

	return xdrgen_encode_MKDIR3res(xdr, resp);
}

/**
 * nfs_svc_encode_SYMLINK3res - Encode a SYMLINK3res result
 * @rqstp: RPC transaction context
 * @xdr: target XDR data stream
 *
 * Return values:
 *   %true: procedure results encoded successfully
 *   %false: encode failed
 */
bool nfs_svc_encode_SYMLINK3res(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct SYMLINK3res *resp = rqstp->rq_resp;

	return xdrgen_encode_SYMLINK3res(xdr, resp);
}

/**
 * nfs_svc_encode_MKNOD3res - Encode a MKNOD3res result
 * @rqstp: RPC transaction context
 * @xdr: target XDR data stream
 *
 * Return values:
 *   %true: procedure results encoded successfully
 *   %false: encode failed
 */
bool nfs_svc_encode_MKNOD3res(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct MKNOD3res *resp = rqstp->rq_resp;

	return xdrgen_encode_MKNOD3res(xdr, resp);
}

/**
 * nfs_svc_encode_REMOVE3res - Encode a REMOVE3res result
 * @rqstp: RPC transaction context
 * @xdr: target XDR data stream
 *
 * Return values:
 *   %true: procedure results encoded successfully
 *   %false: encode failed
 */
bool nfs_svc_encode_REMOVE3res(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct REMOVE3res *resp = rqstp->rq_resp;

	return xdrgen_encode_REMOVE3res(xdr, resp);
}

/**
 * nfs_svc_encode_RMDIR3res - Encode a RMDIR3res result
 * @rqstp: RPC transaction context
 * @xdr: target XDR data stream
 *
 * Return values:
 *   %true: procedure results encoded successfully
 *   %false: encode failed
 */
bool nfs_svc_encode_RMDIR3res(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct RMDIR3res *resp = rqstp->rq_resp;

	return xdrgen_encode_RMDIR3res(xdr, resp);
}

/**
 * nfs_svc_encode_RENAME3res - Encode a RENAME3res result
 * @rqstp: RPC transaction context
 * @xdr: target XDR data stream
 *
 * Return values:
 *   %true: procedure results encoded successfully
 *   %false: encode failed
 */
bool nfs_svc_encode_RENAME3res(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct RENAME3res *resp = rqstp->rq_resp;

	return xdrgen_encode_RENAME3res(xdr, resp);
}

/**
 * nfs_svc_encode_LINK3res - Encode a LINK3res result
 * @rqstp: RPC transaction context
 * @xdr: target XDR data stream
 *
 * Return values:
 *   %true: procedure results encoded successfully
 *   %false: encode failed
 */
bool nfs_svc_encode_LINK3res(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct LINK3res *resp = rqstp->rq_resp;

	return xdrgen_encode_LINK3res(xdr, resp);
}

/**
 * nfs_svc_encode_READDIR3res - Encode a READDIR3res result
 * @rqstp: RPC transaction context
 * @xdr: target XDR data stream
 *
 * Return values:
 *   %true: procedure results encoded successfully
 *   %false: encode failed
 */
bool nfs_svc_encode_READDIR3res(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct READDIR3res *resp = rqstp->rq_resp;

	return xdrgen_encode_READDIR3res(xdr, resp);
}

/**
 * nfs_svc_encode_READDIRPLUS3res - Encode a READDIRPLUS3res result
 * @rqstp: RPC transaction context
 * @xdr: target XDR data stream
 *
 * Return values:
 *   %true: procedure results encoded successfully
 *   %false: encode failed
 */
bool nfs_svc_encode_READDIRPLUS3res(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct READDIRPLUS3res *resp = rqstp->rq_resp;

	return xdrgen_encode_READDIRPLUS3res(xdr, resp);
}

/**
 * nfs_svc_encode_FSSTAT3res - Encode a FSSTAT3res result
 * @rqstp: RPC transaction context
 * @xdr: target XDR data stream
 *
 * Return values:
 *   %true: procedure results encoded successfully
 *   %false: encode failed
 */
bool nfs_svc_encode_FSSTAT3res(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct FSSTAT3res *resp = rqstp->rq_resp;

	return xdrgen_encode_FSSTAT3res(xdr, resp);
}

/**
 * nfs_svc_encode_FSINFO3res - Encode a FSINFO3res result
 * @rqstp: RPC transaction context
 * @xdr: target XDR data stream
 *
 * Return values:
 *   %true: procedure results encoded successfully
 *   %false: encode failed
 */
bool nfs_svc_encode_FSINFO3res(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct FSINFO3res *resp = rqstp->rq_resp;

	return xdrgen_encode_FSINFO3res(xdr, resp);
}

/**
 * nfs_svc_encode_PATHCONF3res - Encode a PATHCONF3res result
 * @rqstp: RPC transaction context
 * @xdr: target XDR data stream
 *
 * Return values:
 *   %true: procedure results encoded successfully
 *   %false: encode failed
 */
bool nfs_svc_encode_PATHCONF3res(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct PATHCONF3res *resp = rqstp->rq_resp;

	return xdrgen_encode_PATHCONF3res(xdr, resp);
}

/**
 * nfs_svc_encode_COMMIT3res - Encode a COMMIT3res result
 * @rqstp: RPC transaction context
 * @xdr: target XDR data stream
 *
 * Return values:
 *   %true: procedure results encoded successfully
 *   %false: encode failed
 */
bool nfs_svc_encode_COMMIT3res(struct svc_rqst *rqstp, struct xdr_stream *xdr)
{
	struct COMMIT3res *resp = rqstp->rq_resp;

	return xdrgen_encode_COMMIT3res(xdr, resp);
}
